---
title: "Taller 2"
date: "2023-08-24"
lang: es
website:
  comments:
    giscus:
      repo: kevin-carrasco/investigacion-cuantitativa
---

```{r setup, include=FALSE, cache = TRUE}
require("knitr")
opts_chunk$set(warning=FALSE,
             message=FALSE,
             echo=TRUE,
             cache = TRUE, fig.width=7, fig.height=5.2)
```

# Objetivo del taller

Reforzar los procedimientos de operacionalización y construcción de indicadores sociales.


# Instrucciones: 

A continuación, se les presentarán diversos indicadores sociales, junto a sus definiciones. En sus grupos de trabajo, ustedes deben: 

a) Seleccionar dos de los indicadores especificados en la siguiente sección.

b) En base a la definición presentada, determinar qué variables se necesitan para medir el fenómeno.

c) Expresar matemáticamente la fórmula con la que debiera estimarse el indicador.

d) Especificar los valores posibles que puede adoptar el indicador, en base a la fórmula elaborada.

e) Señalar cómo interpretar aquellos valores. Por ejemplo, qué implica que un valor A sea mayor que B, qué implica un valor mínimo o un valor máximo (en caso de que existan), entre otros. También se puede presentar un ejemplo de estimación.

f) Especificar al menos una limitación y una potencialidad del indicador.

g) Presentar dos ejemplos de política pública que podrían utilizar esta información como insumo para su implementación.

h) En una hoja deben especificar el título Taller 2, el nombre de l_s integrantes del equipo, y sus respectivas respuestas. Tendrán hasta las 13:25 para realizar el taller.


## Indicadores:

1) Tasa de ocupación informal: porcentaje de Ocupados Informales respecto al total de los Ocupados del periodo de referencia (INE, 2021). Ello involucra a todas las personas cuyo trabajo no cuenta con características como un contrato escrito, pago a través de liquidaciones de sueldo, entre otros.

2) Distribución de población indígena por comuna: porcentaje de habitantes en cada comuna que se identifican como pertenecientes a un pueblo indígena.

3) Concentración de jefas de hogar según composición familiar: porcentaje de mujeres que adoptan el rol de jefas de hogar en hogares de distinta composición familiar (unipersonal, nuclear sin hij_s, nuclear con hij_s y monomaternal) respecto del total de jefas de hogar.

4) Índice de hacinamiento: razón entre el número de personas y el número de habitaciones usadas como dormitorios en una vivienda.

5) Tasa de atención médica ante problema de salud: porcentaje de personas que, habiendo tenido un problema de salud, pudieron recibir atención médica.


## Ejemplo de trabajo

Indicador: Tasa de Inflación

Definición: Variación porcentual de un Índice de Precios de Consumo (IPC) respecto del periodo anterior. El IPC es un indicador que mide la variación media de bienes y servicios durante un período de tiempo determinado en una economía en específico.

Variables necesarias: Precios de los bienes y servicios incluidos en la estimación del IPC para el periodo por analizar y el periodo anterior.

Formalización: 

$$TI = \frac{IPC1-IPC0}{IPC0} * 100$$ 

donde:

TI = Tasa de Inflación,

IPC1 = IPC del periodo por analizar 

IPC0 = IPC del periodo anterior

Posibles valores: (- ∞, +∞) medidos en porcentaje (%).

Interpretación: un valor positivo indica un aumento medio relativo del conjunto de precios de los bienes y servicios incluidos en la estimación del IPC, mientras que un valor negativo indica una disminución media relativa del conjunto de precios de los bienes y servicios incluidos en la estimación del IPC. Por ejemplo, una tasa de inflación de un 3,4% indica que, en promedio, el conjunto de los precios de bienes y servicios incluidos en la estimación del IPC aumentó en un 3.4% respecto del periodo anterior. Así, si un producto X tenía un precio de $1.000 en el periodo anterior, su precio en el periodo analizado debiese aproximarse a 1.000*1.034 = $1.034.

Limitaciones: La definición de bienes y servicios incluidos en la estimación del IPC puede estar sujeta a lo que el gobierno o l_s funcionari_s del Estado consideren indispensable en los gastos mensuales de un hogar, dejando fuera algunos que pudiesen tener igual relevancia.

Potencialidades: Permite medir de forma precisa los requerimientos de un hogar promedio mensual en relación a sus gastos fundamentales, por lo que hace posible conocer el estado de una economía en lo que respecta a su consumo.

Ej. de PP: Transferencias directas a hogares de bajos ingresos, para facilitar la satisfacción de necesidades básicas. Subvención gubernamental del precio de los productos con mayor aumento de precios entre ambos periodos.
