---
title: "Presentación"
subtitle: "R para análisis estadístico"
linktitle: "Presentación"
date: "2024-06-18"
lang: es
---

## Rúbrica de Evaluación Presentaciones

| Nota máxima | Criterios |
|-------------|-----------|
| **7,0**      | La presentación cumple con todos los aspectos estéticos del trabajo: La presentación es realizada a través de Quarto presentations subida y visualizada en Github pages. Junto con esto la presentación es desarrollada de buena manera considerando los aspectos más relevantes del trabajo de investigación: Tema de investigación bien planteado; objetivos claros y coherentes en concordancia con métodos cuantitativos; presentación de los principales resultados de la investigación; presentación de conclusiones. |
| **6,0**      | La presentación desarrolla de buena manera los aspectos incluidos en el punto anterior pero tiene algunos errores que afectan su calidad global—por ejemplo presentación no disponible en github pages; objetivos mal planteados y no alineados con un diseño cuantitativo; falencias en la presentación e interpretación de resultados. |
| **5,0**      | La presentación desarrolla parcialmente lo pedido en el primer punto incurriendo en errores en algunos aspectos centrales (por ejemplo presentación en otro formato) o no desarrollando adecuadamente otros puntos (ej. No presentando correctamente gráficos). |
| **4,0**      | La presentación contiene errores persistentes y no cuenta con elementos que permitan demostrar un dominio básico de lo solicitado en el primer punto (por ejemplo tema no acorde con los resultados presentados; no presenta gráficos que resuman los resultados). |
| **3,0**      | La presentación es de calidad deficiente y sugiere que los/as estudiantes no tienen conocimientos mínimos requeridos para aprobar el curso. Esto más allá de que algunos aspectos formales estén correctos. |
| **2,0**      | La presentación no tiene ningún elemento que amerite ser evaluado en el marco de lo pedido en el primer punto más allá de formalidades mínimas. |
| **1,0**      | No asiste a la presentación y no presenta justificativo. |
