---
title: "Taller 5"
date: "2023-11-09"
lang: es
website:
  comments:
    giscus:
      repo: kevin-carrasco/investigacion-cuantitativa
---


# Objetivo del taller

Iniciar el desarrollo del segundo trabajo grupal asociado a construcción de cuestionarios.


# Instrucciones: 

En sus grupos de trabajo, ustedes deben:

1. Definir un tema principal a partir del cual elaborarán el cuestionario (por ejemplo: condiciones y estrategias de estudio, actitudes y prácticas deportivas, entre otros). La elección del tema es libre y depende de los intereses de quienes conformen el grupo.

2. Buscar en internet al menos tres encuestas o cuestionarios que aborden temas similares al que han elegido. En base a sus respectivos documentos metodológicos, deben especificar:
  a) Nombre de la encuesta;
  
  b) Año(s) y país(es) en que se ha levantado;

  c) Institución/organismo/etc. encargado de su ejecución;

  d) Objetivos de la encuesta;

  e) Población objetivo;

  f) Principales variables del estudio; y

  g) Recuento de los módulos del cuestionario, junto a un breve resumen que dé cuenta de los temas abordados en cada uno.

3. Para cada cuestionario revisado, señalar al menos dos variables que puedan ser útiles para el cuestionario que elaborarán en el transcurso del segundo trabajo. Deben incluir el enunciado y sus respectivas alternativas de respuesta.

4. En base a lo revisado anteriormente, y pensando en el cuestionario que elaborarán en el marco del trabajo, definan:

  a) Objetivo de su estudio;

  b) Población objetivo a la cual está dirigido; y

  c) Principales variables a considerar.
  
5. En una hoja deben especificar el título Taller 5, el nombre de l_s integrantes del equipo que están presentes en el taller, y sus respectivas respuestas. Tendrán hasta las 13:25 para realizar el taller.
