---
title: "Planificación"
sidebar: false
toc: false
page-layout: full
---

Los tres componentes centrales del curso son las clases teóricas, los prácticos en R y los trabajos. Las **clases** se realizarán los días **Miércoles 08:30 a 09:50** en sala **E67**. Los **prácticos en R** se realizarán el mismo día en el horario de **10:00 a 11:20**.

-   [**Clases**]() (<i class="fas fa-chalkboard-teacher"></i> ): Lecturas, documentos de presentación y sesiones teóricas

-   [**Talleres y actividades en R**]() (<i class="fas fa-user-edit"></i>): Actividades prácticas a desarrollar en el segundo bloque de la clase, según programación al final de esta página.

-   [**Lecturas**]() (<i class="fas fa-book-reader"></i>): Llegar a la clase con los textos leídos.

+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                              | # <i class="fas fa-chalkboard-teacher"></i> Clases                      | # <i class="fas fa-user-edit"></i> Talleres y prácticos en R | # <i class="fas fa-book-reader"></i> Lecturas y material adicional                                                                                                                                                                                                                                                             |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <font color="orange"> **Agosto** </font>     |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 14                                 | Introducción                                                            | Práctico 1                                                   | \- [Ritchey, F. 2002. Estadísticas para las Ciencias Sociales: El potencial de la imaginación estadística”. México: Mc Graw Hill. Capítulo. 13](https://estadisticaiv.netlify.app/files/ritchey2002.pdf)                                                                                                                       |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Presentación del curso                                              |                                                              | \- [Moore, D.S. (2005). Estadística básica aplicada. Capítulo 6 “Introducción a la inferencia estadística”.](https://estadisticaiv.netlify.app/files/moore2005.pdf)                                                                                                                                                            |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Repaso de conceptos centrales para entender el análisis estadístico |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 21                                 | Unidad 1                                                                | Práctico 2                                                   | \- [Moore, D.S. Estadística básica aplicada. Capítulo 9 “Inferencia para tablas de contingencia”.](https://estadisticaiv.netlify.app/files/moore2005.pdf)                                                                                                                                                  |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Chi-cuadrado                                                        |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 28                                 | Unidad 1                                                                | Práctico 3                                                   | \- [Capítulos 1-5: Greenacre, M. La práctica del análisis de correspondencias.](https://estadisticaiv.netlify.app/files/grenacre2008.pdf) - [Capítulo 6 “Correspondence Analysis”: Friendly y Meyer. Discrete Data Analysis with R.](https://estadisticaiv.netlify.app/files/friendly_meyer.pdf)            |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Análisis de correspondencia simple                                  |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <font color="orange"> **Septiembre** </font> |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 04                                 | Unidad 1                                                                | Práctico 4                                                   | \- [Capítulos 6-10: Greenacre, M. La práctica del análisis de correspondencias.](https://estadisticaiv.netlify.app/files/grenacre2008.pdf) - [Capítulo 6 “Correspondence Analysis”: Friendly y Meyer. Discrete Data Analysis with R.]((https://estadisticaiv.netlify.app/files/friendly_meyer.pdf))  |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Análisis de correspondencia múltiple                                |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | **Trabajo 1 (25%): se entrega pauta, UNA semana para entregar.**        |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 11                                 | Unidad 1                                                                | Trabajo 1                                                    |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | Clase resolución dudas / preparación trabajo 1.                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | **Estudiantes entregan trabajo 1 (25%).**                               |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 25                                 | Unidad 2                                                                | Práctico 5                                                   | \- Moore, D. Estadística básica aplicada. Capítulo 2 “Análisis de relaciones”.                                                                                                                                                                                                                                                 |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Correlación y regresión lineal                                      |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <font color="orange"> **Octubre** </font>    |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 02                                 | Unidad 2                                                                | Práctico 6                                                   | \- Ancona, M. A. Análisis multivariable. Capítulo 5 “Análisis factorial”. Cea D’.                                                                                                                                                                                                                                              |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Alfa de Cronbach                                                    |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Análisis de Componentes Principales / Análisis Factorial (parte 1)  |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 09                                 | Unidad 2                                                                | Práctico 7                                                   | \- Lloret-Segura, et al. “El análisis factorial exploratorio de los ítems: una guía práctica, revisada y actualizada.”                                                                                                                                                                                                         |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Análisis de Componentes Principales / Análisis Factorial (parte 2)  |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 16                                 | Unidad 2                                                                | Práctico 8                                                   | \- Capítulo 17 “Exploratory factor analysis”: Field. Discovering statistics using R.                                                                                                                                                                                                                                           |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Análisis de Componentes Principales / Análisis Factorial (parte 3)  |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | **Trabajo 2  (25%): se entrega pauta, UNA semana para entregar.**       |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 23                                 | Unidad 2                                                                | Trabajo 2                                                    |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | Clase resolución dudas / preparación trabajo 2.                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | **Estudiantes entregan trabajo 2 (25%).**                               |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 30                                 | Unidad 3                                                                | Práctico 9                                                   | \- Cea D’ Ancona, M. A. Análisis multivariable. Capítulo 3 “Análisis de conglomerados”.                                                                                                                                                                                                                                        |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Análisis de conglomerados (parte 1)                                 |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <font color="orange"> **Noviembre** </font>  |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 06                                 | Unidad 3                                                                | Práctico 10                                                  | \- Cea D’ Ancona, M. A. Análisis multivariable. Capítulo 3 “Análisis de conglomerados”.                                                                                                                                                                                                                                        |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Análisis de conglomerados (parte 2)                                 |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 13                                 | Unidad 3                                                                | Práctico 11                                                  | \- Cea D’ Ancona, M. A. Análisis multivariable. Capítulo 3 “Análisis de conglomerados”.                                                                                                                                                                                                                                        |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | -   Análisis de conglomerados (parte 3)                                 |                                                              | \- Giordani et al. An Introduction to Clustering with R. Parte 2 “Standard Clustering”.                                                                                                                                                                                                                                        |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | **Trabajo 3  (25%): se entrega pauta, UNA semana para entregar.**       |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 20                                 | Unidad 3                                                                | Trabajo 3                                                    |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | Clase resolución dudas / preparación trabajo 3.                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
|                                              | **Estudiantes entregan trabajo 3 (25%)**                                |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 27                                 | Clase resolución dudas                                                  |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <font color="orange"> **Diciembre** </font>  |                                                                         |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 04                                 | EXAMEN (25%)                                                            |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Miércoles 11                                 | EXAMEN DE REPETICIÓN                                                    |                                                              |                                                                                                                                                                                                                                                                                                                                |
+----------------------------------------------+-------------------------------------------------------------------------+--------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
