---
title: Programa
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

::: {.grid .course-details .course-details-smaller}

::: {.g-col-6}
### Profesor

- {{< fa user >}} &nbsp; [{{< var instructor.name >}}]({{< var instructor.url >}})
- {{< fa university >}} &nbsp; {{< var instructor.office >}}
- {{< fa envelope >}} &nbsp; <a href="mailto:{{< var instructor.email >}}">{{< var instructor.email >}}</a>
- {{< fa brands twitter >}} &nbsp; [{{< var instructor.twitter >}}](https://www.twitter.com/{{< var instructor.twitter >}})
:::

::: {.g-col-6}
### Detalles del curso

- {{< fa calendar >}} &nbsp; {{< var course.days >}}
- {{< fa calendar-alt >}} &nbsp; {{< var course.dates >}}
- {{< fa clock >}} &nbsp; {{< var course.time >}}
- {{< fa location-dot >}} &nbsp; {{< var course.location >}}
:::

:::

## Propósito general del curso

Se espera que al término del curso los y las estudiantes puedan elaborar y analizar diseños de investigación social de carácter cuantitativo, así como describir cuantitativamente un conjunto de datos utilizando el lenguaje R. En ese sentido, se profundizará el uso de R y la interfaz de RStudio para su uso en contextos académicos, así como el uso de otros sistemas de publicaciones como Quarto. Al mismo tiempo, el curso profundiza en temas relevantes para las ciencias sociales como el análisis estadístico, pero con un foco específico en la presentación de resultados (visualización de datos) a través de documentos dinámicos.

### Objetivos específicos

- Conocer y aplicar instrumentos de medición y tipos de estudios cuantitativos.

- Interpretar y analizar los elementos centrales de una base de datos con información social.

- Presentar resultados a partir de la visualización de datos y construcción de documentos dinámicos en R (Quarto).

- Aplicar, interpretar y visualizar técnicas de estadística descriptiva según las distintas características de los datos en R.

- Aplicar e interpretar técnicas de estadística correlacional e inferencia estadística para muestras complejas en R.

- Aplicar, interpretar y visualizar técnicas de regresión lineal y logística para variables numéricas y variables categóricas en R.


## Contenidos

### Unidad 1: Elementos y herramientas de R

1.1 R enviroment: interfaz de RStudio, elementos de script, workspace

1.2 Herramientas para la colaboración y comunicación: Rproject, GitHub, Zotero y Slack

1.3 Protocolo IPO para la reproducibilidad de investigaciones sociales

1.4 Construcción de reportes automáticos, reproducibles e integrados con código: Quarto

### Unidad 2: Operacionalización y análisis descriptivo de datos

2.1 Operacionalización y niveles de medición

2.2 Tidy data: unir, dividir, filtrar, ordenar y exportar datos en R

2.3 Recodificación de variables: descriptivos básicos, casos perdidos, etiquetamiento de variables

2.4 Agrupación de datos y construcción de variables a partir de datos existentes

2.5 Tablas descriptivas y tablas de contingencia

2.6 ggplot2: gráficos de barra, de caja, dispersión e histograma

### Unidad 3: Análisis estadístico inferencial en R

3.1 Análisis bivariado: Correlación de Pearson y ANOVA

3.2 Muestras complejas e inferencia estadística con survey y srvyr

### Unidad 4: Regresión lineal y regresión logística

4.2 Regresiones lineales de mínimos cuadrados ordinarios

4.3 Interpretación de coeficientes (variables cuantitativas y cualitativas)

4.4 Aspectos básicos de regresión logística

4.5 Representación gráfica de coeficientes de regresión lineal y logística (probabilidades predichas)


## Metodología

Se tendrán tres espacios principales de aprendizaje:

1. Sesiones de clases lectivas, donde se presentarán los aspectos centrales de los contenidos correspondientes a la semana. Estas se desarrollarán en el primer bloque del martes. 

2. Prácticas guiadas: cada tema de las sesiones se acompaña de una guía práctica de aplicación de contenidos. Estas guías están diseñadas para ser desarrolladas de manera autónoma por cada estudiante semana a semana. También serán desarrolladas y revisadas cada semana por el profesor y/o ayudantes para dar mayor oportunidad de participación y resolver las dudas respectivas. Estas se desarrollan en el segundo bloque del martes. 

3. Evaluaciones: se desarrollarán trabajos periódicos que permitirán a las/os estudiantes aplicar contenidos y replicar lo aprendido en los prácticos en base a una base de datos seleccionada por ellas/os a inicio de semestre. Esto permitirá no solo recibir retroalimentación constante, sino que aprender con datos que puedan ser útiles para otros proyectos de investigación. Al finalizar el curso, el/la estudiante deberá entregar un proyecto de investigación que incluya todo el trabajo de estas tareas, así como la incorporación de comentarios y sugerencias de retroalimentación de las evaluaciones. Además, el/la estudiante deberá realizar una presentación de resultados en formato académico/conferencia.

Las instrucciones de las tareas serán publicadas con una semana de anticipación a su entrega.

## Recursos principales de aprendizaje y comunicación

1. Sitio web

El curso estará disponible en un sitio web programado por el docente, en tanto permite integrar texto y código de R.     

2. R, RStudio y RStudio Cloud

El software que se utilizará principalmente será R y su interfaz RStudio. Ahora bien, muchos usuario/as de R presentan problemas de instalación dada la capacidad de sus computadores y sistemas operativos. Por ello, para quienes tengan estos problemas se promoverá el uso del servicio gratuito de RStudio.cloud           

3. Slack

Slack es una herramienta de uso frecuente en equipos de trabajo que utilizan R pues permite integrar script de distintos lenguajes en el chat. Se tendrá un espacio de trabajo en la app Slack que permite que cualquier persona del curso pueda hacer preguntas y cualquiera pueda responder. Esta es una de las prácticas que se promoverán en el curso pues es probable que los/as estudiantes tengan dudas similares a las de sus compañeros, por lo que las respuestas del docente, ayudantes y otros compañeros/as serán de libre disposición de todo el curso. Dentro de Slack se tendrán canales específicos para hacer preguntas sobre las sesiones, tareas y proyectos, y el link que permite unirse a este estará disponible en el sitio del curso.

4. GitHub

Github es una plataforma online que permite depositar archivos y el control de versiones (VCS), por lo que se ha transformado en una herramienta fácil y popular para corregir, colaborar y compartir códigos de distintos lenguajes (no solo R). Utilizaremos esta plataforma para subir las tareas, ayudarlos/as de manera directa con su código y darles feedback. 


## Evaluación de aprendizaje

Las evaluaciones del curso se componen de tareas (60% de la nota final), la entrega de una investigación (30% de la nota final) y una presentación (10% de la nota final), en dónde en todos los casos la/el estudiante deberá seleccionar datos y temas de interés de modo de acercar la aplicación del software a contextos de investigación propios de la/el estudiante. En concreto, cada evaluación consiste en:

1. Trabajos (60% de la nota final): consisten en evaluaciones parciales temáticas que buscan poner en práctica los aprendizajes expuestos en la sesión de clases y herramientas reforzadas en los prácticos. Durante el semestre se realizarán 4 tareas (15% c/u).

2. Presentación final (10% de la nota final): Consiste en una presentación final individual que resuma el trabajo realizado en el proyecto de investigación. Al tratarse de un curso metodológico, más que los fundamentos teóricos de la investigación, el foco de la presentación debe estar centrado en los resultados de la investigación (visualización de resultados) y en reflexiones de toma de decisiones metodológicas en términos de apertura y reproducibilidad.

3. Investigación final (examen) (30% de la nota final): consiste en una evaluación final individual que aplica los conocimientos y herramientas entregadas a lo largo del curso y en las tareas realizadas, a un proyecto de investigación de elección por el/la estudiante. Se espera que este proyecto incluya todo el trabajo de estas tareas, así como la incorporación de comentarios y sugerencias de retroalimentación de las evaluaciones. 


## Información general

Los/as alumnas/os que no se presenten o entreguen una evaluación por enfermedad deben hacer llegar el certificado médico a coordinación en el plazo establecido por el reglamento. Quienes no lo hagan serán evaluados con nota 1,0. Las pruebas atrasadas serán reprogramadas la primera semana de junio.

Ningún curso podrá ser aprobado si no cuenta con el mínimo del 70% de asistencia. Tendrán derecho a rendir los exámenes todos los/as estudiantes que hayan cumplido con la exigencia de asistencia mínima al curso y cuyo promedio de notas sea igual o superior a 3,5.

Los/as estudiantes podrán eximirse de la obligación de rendir los exámenes finales de cada curso. Al iniciarse el semestre académico, cada profesor/a deberá indicar a los/as estudiantes en el programa del curso si existe la posibilidad de eximirse y bajo qué condiciones. Con todo, no será posible eximirse de examen alguno si el/a estudiante no tiene una nota promedio igual o superior a 5,5 y una asistencia igual o superior al 70% de las clases efectivamente realizadas en el respectivo curso.

## Reglamento Académico del Estudiante de Pregrado.

Art. 23.- Cualquier conducta de un estudiante que tienda a viciar la evaluación de actividades académicas o que constituya fraude académico, figura que contempla irregularidades tales como copia, suplantación o alteración de evaluaciones, plagio, faltas a la ética profesional, sin que esta enumeración sea taxativa, dará origen a las siguientes sanciones, según la gravedad de la falta cometida: (i) nota mínima 1,0 (uno) en la respectiva evaluación; (ii) reprobación del curso respectivo; (iii) amonestación; (iv) permanencia condicional; (v) suspensión de actividades académicas por un período académico; (vi) expulsión de la Universidad.

Asimismo, toda actividad de un estudiante que entorpezca gravemente y/o dificulte el normal desarrollo académico, podrá ser sancionada de conformidad a las disposiciones establecidas en el Reglamento de Conducta y Convivencia de la Universidad Alberto Hurtado. 

Art. 24.- Las dos primeras sanciones previstas en el artículo anterior, a saber (i) Nota mínima 1,0; y (ii) Reprobación del Curso respectivo, son prerrogativa del docente a cargo de la asignatura, quien deberá informarlas a la Dirección de la Carrera.

***Para evitar el plagio todo trabajo, composición o material documental que los estudiantes realicen debe citar adecuadamente las fuentes utilizadas, ya sea a través del sistema APA (American Psychological Association) http://www.apastyle.org o MLA (Modern Language Association) http://www.mla.org/.

