<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="R para Análisis estadístico">

<title>R para Análisis estadístico - Resumen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="..//files/icon-512.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>


<meta property="og:title" content="R para Análisis estadístico - Resumen">
<meta property="og:description" content="R data analisis">
<meta property="og:image" content="https://R-analisis-datos.netlify.app/files/social-image-sp23.png">
<meta property="og:site_name" content="R para Análisis estadístico">
<meta property="og:locale" content="en_US">
<meta name="twitter:title" content="R para Análisis estadístico - Resumen">
<meta name="twitter:description" content="R data analisis">
<meta name="twitter:image" content="https://R-analisis-datos.netlify.app/files/social-image-sp23.png">
<meta name="twitter:creator" content="@KevinCarrascoQ1">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">R para Análisis estadístico</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../syllabus.html"> 
<span class="menu-text">Programa</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../schedule.html"> 
<span class="menu-text">Planificación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../content/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../practicos/index.html" aria-current="page"> 
<span class="menu-text">Prácticos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../herramientas/index.html"> 
<span class="menu-text">Herramientas</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../assignment/index.html"> 
<span class="menu-text">Trabajos</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://rstudio.cloud"> <i class="bi bi-cloud-fill" role="img" aria-label="RStudio.cloud">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../practicos/01-content.html">Talleres</a></li><li class="breadcrumb-item"><a href="../practicos/resumen-content.html">08: Resumen</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Información general</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Actividades prácticas en R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Talleres</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/01-content.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01: Práctico 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/02-content.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02: Práctico 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/03-content.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03: Práctico 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/04-content.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04: Práctico 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/05-content.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">05: Práctico 5</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/06-content.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">06: Práctico 6</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/07-content.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">07: Práctico 7</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../practicos/resumen-content.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">08: Resumen</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En esta página</h2>
   
  <ul>
  <li><a href="#presentación" id="toc-presentación" class="nav-link active" data-scroll-target="#presentación">Presentación</a>
  <ul>
  <li><a href="#objetivo-de-la-práctica" id="toc-objetivo-de-la-práctica" class="nav-link" data-scroll-target="#objetivo-de-la-práctica">Objetivo de la práctica</a></li>
  </ul></li>
  <li><a href="#preparación" id="toc-preparación" class="nav-link" data-scroll-target="#preparación">Preparación</a>
  <ul>
  <li><a href="#flujo" id="toc-flujo" class="nav-link" data-scroll-target="#flujo">Los procesos de preparación y análisis vinculados a datos y resultados se presentan en el siguiente esquema:</a></li>
  <li><a href="#antecedentes-de-los-datos-a-utilizar" id="toc-antecedentes-de-los-datos-a-utilizar" class="nav-link" data-scroll-target="#antecedentes-de-los-datos-a-utilizar">Antecedentes de los datos a utilizar</a></li>
  <li><a href="#librerias" id="toc-librerias" class="nav-link" data-scroll-target="#librerias">1. Librerías principales (de R) a utilizar en el análisis</a></li>
  <li><a href="#cargar-base-de-datos" id="toc-cargar-base-de-datos" class="nav-link" data-scroll-target="#cargar-base-de-datos">2. Cargar base de datos</a></li>
  <li><a href="#selección-de-variables-a-utilizar" id="toc-selección-de-variables-a-utilizar" class="nav-link" data-scroll-target="#selección-de-variables-a-utilizar">3. Selección de variables a utilizar</a></li>
  <li><a href="#procesamiento-de-variables" id="toc-procesamiento-de-variables" class="nav-link" data-scroll-target="#procesamiento-de-variables">Procesamiento de variables</a>
  <ul class="collapse">
  <li><a href="#cohesión-barrial" id="toc-cohesión-barrial" class="nav-link" data-scroll-target="#cohesión-barrial">cohesión barrial</a>
  <ul class="collapse">
  <li><a href="#educación" id="toc-educación" class="nav-link" data-scroll-target="#educación">4.2. Educación</a></li>
  </ul></li>
  <li><a href="#sexo" id="toc-sexo" class="nav-link" data-scroll-target="#sexo">4.3. Sexo</a></li>
  <li><a href="#edad" id="toc-edad" class="nav-link" data-scroll-target="#edad">4.4 Edad</a></li>
  </ul></li>
  <li><a href="#generación-de-base-de-datos-procesada-para-el-análisis" id="toc-generación-de-base-de-datos-procesada-para-el-análisis" class="nav-link" data-scroll-target="#generación-de-base-de-datos-procesada-para-el-análisis">5. Generación de base de datos procesada para el análisis</a></li>
  </ul></li>
  <li><a href="#análisis" id="toc-análisis" class="nav-link" data-scroll-target="#análisis">Análisis</a>
  <ul>
  <li><a href="#análisis-descriptivo" id="toc-análisis-descriptivo" class="nav-link" data-scroll-target="#análisis-descriptivo">Análisis descriptivo</a></li>
  <li><a href="#asociación-de-variables" id="toc-asociación-de-variables" class="nav-link" data-scroll-target="#asociación-de-variables">Asociación de variables</a></li>
  <li><a href="#construcción-de-escala" id="toc-construcción-de-escala" class="nav-link" data-scroll-target="#construcción-de-escala">Construcción de escala</a></li>
  </ul></li>
  <li><a href="#subir-a-github" id="toc-subir-a-github" class="nav-link" data-scroll-target="#subir-a-github">Subir a github</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../practicos/01-content.html">Talleres</a></li><li class="breadcrumb-item"><a href="../practicos/resumen-content.html">08: Resumen</a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Resumen</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostrar todo el código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Ocultar todo el código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver el código fuente</a></li></ul></div></div>
<p class="subtitle lead">R data analisis</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Fecha de publicación</div>
    <div class="quarto-title-meta-contents">
      <p class="date">7 de mayo de 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="presentación" class="level1">
<h1>Presentación</h1>
<section id="objetivo-de-la-práctica" class="level2">
<h2 class="anchored" data-anchor-id="objetivo-de-la-práctica">Objetivo de la práctica</h2>
<p>Como siempre, estas guías no apuntan a ser un <strong>paso a paso</strong> de lo que se debe hacer, sino que son un ejemplo concreto de cómo hacer ciertos tipos de análisis con un conjunto de datos determinados. Los procedimientos de limpieza van a depender siempre del conjunto de datos que utilicemos en nuestras investigaciones y el proceso de análisis va a depender de nuestros objetivos de investigación, en relación con las variables e hipótesis que queramos demostrar.</p>
<p>El desarrollo de esta guía tiene por objetivo revisar todos los contenidos trabajados hasta este momento del curso (07/05/2024). En términos generales, es un resumen de las cosas esenciales de los 7 prácticos anteriores como limpieza y preparación de datos, análisis descriptivo, bivariado y visualización de datos en Quarto y subida a github y visualización de github pages.</p>
<p>En concreto, un ejemplo del resultado final de un trabajo se debería poder visualizar así en un <a href="https://github.com/Kevin-carrasco/ipo">repositorio de github</a> y en <a href="https://kevin-carrasco.github.io/ipo/trabajo.html">Github pages</a></p>
<p>Por temas de orden y reproducibilidad, en este curso hemos separado en <strong>dos momentos</strong> el trabajo con datos, y dos archivos de código correspondientes:</p>
<ul>
<li><p><strong>Preparación</strong> corresponde a lo que se conoce generalmente como “limpieza”, es decir, realizar las modificaciones necesarias para poder efectuar los análisis. Estas modificaciones previas al análisis son necesarias ya que los datos originales con los que se va a trabajar en general no vienen perfectamente adaptados a los análisis que se quieren hacer. Por lo tanto, en cuanto a datos también hacemos la distinción entre datos originales y datos preparados (o procesados). Este código de análisis lo podemos encontrar en la carpeta <a href="https://github.com/Kevin-carrasco/ipo/tree/main/processing">procesamiento</a> del repositorio</p></li>
<li><p><strong>Análisis</strong>: se relaciona tanto con análisis descriptivos asociados a las preguntas de investigación y como también modelamiento de datos para contrastar hipótesis de investigación. En este curso lo esencial es visualizar el análisis a través de quarto, por lo que el <a href="https://github.com/Kevin-carrasco/ipo/blob/main/trabajo.qmd">documento .qmd</a> debería estar en el inicio del repositorio (junto al Rproject). Este documento se debe renderizar y obtenemos un <a href="https://github.com/Kevin-carrasco/ipo/blob/main/trabajo.html">archivo .html</a> que se podría visualizar a través de github pages en, por ejemplo, el link: <a href="https://kevin-carrasco.github.io/ipo/trabajo.html">https://kevin-carrasco.github.io/ipo/trabajo.html</a>. Dónde:</p></li>
</ul>
<p><img src="../files/img/url-pages.png" class="img-fluid"></p>
<p><strong>Vamos paso a paso</strong></p>
</section>
</section>
<section id="preparación" class="level1">
<h1>Preparación</h1>
<section id="flujo" class="level2">
<h2 class="anchored" data-anchor-id="flujo">Los procesos de preparación y análisis vinculados a datos y resultados se presentan en el siguiente esquema:</h2>
<p><img src="images/produccion.png" class="img-fluid"></p>
<p>Tanto la preparación como el análisis (que son parte del concepto más general de procesamiento) quedan registrados cada uno en un <em>archivo de código</em>.</p>
<p><span class="sidenote"><strong>Archivo de código R</strong>: archivo con extensión .R donde se almacena el código de análisis. Para generarlo desde RStudio: <em>File &gt; New File &gt; R Script</em> (o ctrl+shift+N), y para grabarlo <em>File &gt; Save (o ctrl+s)</em>, y darle nombre la primera vez (recordar: sin tilde ni ñ, y evitar espacios) </span></p>
<p>El documento de <strong>código de preparación</strong> posee 5 partes, más una sección de identificación inicial:</p>
<ol start="0" type="1">
<li>Identificación y descripción general: Título, autor(es), fecha, información breve sobre el contenido del documento</li>
<li>Librerías: cargar librerías a utilizar</li>
<li>Datos: carga de datos</li>
<li>Selección de variables a utilizar</li>
<li>Procesamiento de variables: en este punto, por cada variable se realiza lo siguiente:
<ol type="a">
<li>Descriptivo básico</li>
<li>Recodificación: datos perdidos y valores (en caso de ser necesario)</li>
<li>Etiquetamiento: de variable y valores (en caso de ser necesario)</li>
<li>Otros ajustes</li>
</ol></li>
<li>Generación de base de datos preparada para el análisis.</li>
</ol>
<div class="alert alert-info">
<p><strong>De rutas, estructura de carpetas y otros </strong></p>
<ul>
<li><p><strong>Encontrando la ruta a carpeta local</strong>: lo más fácil es crear la carpeta donde se desean guardar los datos desde el administrador de archivos del computador. Luego, posicionarse con el cursor sobre la carpeta y seleccionar “Propiedades”, en la ventana emergente debería aparecer la ruta hacia la carpeta en “Ubicación”. Copiar esa ruta y agregar al final el nombre de la carpeta (separada por slash)</p></li>
<li><p><strong>Sobre los “slashes” (<code>\</code> o <code>/</code>)</strong>: en la ruta las carpetas y el archivo final aparecen separados por slashes, que según el sistema utilizado pueden ser <em>slash</em> (<code>/</code>) o <em>backslash</em> (<code>\</code>). En R por defecto se usa <em>slash</em>, pero en Windows <em>backslash</em>, por lo que si se usa Windows hay que reemplazarlos por <em>backslash</em> o también puede ser por un doble <em>slash</em> (<code>//</code>).</p></li>
<li><p>Por temas de compatibilidad general, en las rutas se recomienda evitar tildes, eñes, espacios, mayúsculas y guiones bajos (_).</p></li>
<li><p><strong>Estructura de carpetas</strong>: para mantener el orden se sugiere seguir un protocolo de estructura de carpetas de proyecto, para lo que recomendamos el protocolo <a href="https://lisa-coes.com/ipo-protocol/">IPO</a>, y que se adapta al flujo de trabajo presentado anteriormente. Básicamente son tres carpetas: <strong>input</strong>, <strong>procesamiento</strong>, <strong>output</strong>. En la carpeta input crear la subcarpeta data-orig para guardar datos originales, y data-proc para los procesados. En procesamiento se guardan los archivos de código y en output las tablas y los gráficos.</p></li>
</ul>
<p><img src="../files/img/ipo-hex.png" class="img-fluid"></p>
<div>

<p>Nuestras carpetas se deberían ver así:</p>
<p><img src="../files/img/carpetas.png" class="img-fluid"></p>
<p>Donde lo primero que debemos hacer, siempre, es abrir el Rproject (.Rproj) para comenzar nuestro trabajo.</p>
</div></div></section>
<section id="antecedentes-de-los-datos-a-utilizar" class="level2">
<h2 class="anchored" data-anchor-id="antecedentes-de-los-datos-a-utilizar">Antecedentes de los datos a utilizar</h2>
<p>Cohesión barrial con elsoc 2016</p>
</section>
<section id="librerias" class="level2">
<h2 class="anchored" data-anchor-id="librerias">1. Librerías principales (de R) a utilizar en el análisis</h2>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, sjmisc, car, sjlabelled, stargazer, haven, sjPlot, ggplot2, psych)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="cargar-base-de-datos" class="level2">
<h2 class="anchored" data-anchor-id="cargar-base-de-datos">2. Cargar base de datos</h2>
<p><strong>Ajustar espacio de trabajo</strong></p>
<p>Previo a la carga de nuestra base de datos, se recomienda ejecutar los siguientes comandos:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())       <span class="co"># borrar todos los objetos en el espacio de trabajo</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>) <span class="co"># valores sin notación científica</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>La función <code>rm(list=ls())</code> permite comenzar con un espacio de trabajo (environment) vacío y sin otros objetos. Así también, la función <code>options(scipen=999)</code> desactiva la notación científica, es decir, veremos los valores numéricos con todos sus decimales.</p>
<p><strong>Datos</strong></p>
<p>Las bases de datos se pueden cargar de un archivo local o en línea. Para este caso utilizaremos un archivo en línea que viene en formato RData: <strong>elsoc.RData</strong>. <span class="sidenote"><strong>Abrir bases de datos en otros formatos</strong>: Los formatos mas comunes en que se almacenan las bases de datos son .dta (Stata), .sav (Spss) y RData (R). Para abrir desde R utlilizamos la librería <code>haven</code> y sus funciones read_dta y read_sav según corresponda. Ej: <code>datos &lt;- read_dta("base_casen.dta")</code>. Recordar antes instalar/cargar la librería: <code>pacman::p_load(haven)</code> </span></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#cargamos la base de datos desde internet</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://dataverse.harvard.edu/api/access/datafile/7245118"</span>)) <span class="co">#Cargar base de datos</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Realizamos un chequeo básico de la lectura de datos: nombres de las variables y tamaño de la base en términos de casos y variables (en este ejemplo, 18035, 750 ).</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(elsoc_long_2016_2022<span class="fl">.2</span>) <span class="co"># dimension de la base</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18035   750</code></pre>
</div>
</div>
</section>
<section id="selección-de-variables-a-utilizar" class="level2">
<h2 class="anchored" data-anchor-id="selección-de-variables-a-utilizar">3. Selección de variables a utilizar</h2>
<p>Este paso consiste en crear un subset reducido de datos que contenga solo las variables de interés. Para ello lo más fácil es revisar el libro de códigos de cada base de datos. Además filtramos por la ola 1 para trabajar solo con datos del 2016.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> elsoc_long_2016_2022<span class="fl">.2</span> <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ola<span class="sc">==</span><span class="st">"1"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(t02_01, <span class="co"># Este barrio es ideal para mi</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>         t02_02, <span class="co"># Me siento incluido en este barrio</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>         t02_03, <span class="co"># Me identifico con la gente de este barrio</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>         t02_04, <span class="co"># Este barrio es parte de mi</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>         m01,<span class="co"># nivel educacional</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>         m0_sexo,<span class="co"># sexo</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>         m0_edad<span class="co"># edad</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobar</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_data)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "t02_01"  "t02_02"  "t02_03"  "t02_04"  "m01"     "m0_sexo" "m0_edad"</code></pre>
</div>
</div>
<p>Mediante el comando <code>get_label</code> obtenemos el atributo label de las variables.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_data)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                                                       t02_01 
          "Grado de acuerdo: Este es el barrio ideal para mi" 
                                                       t02_02 
     "Grado de acuerdo: Me siento integrado/a en este barrio" 
                                                       t02_03 
"Grado de acuerdo: Me identifico con la gente de este barrio" 
                                                       t02_04 
               "Grado de acuerdo: Este barrio es parte de mi" 
                                                          m01 
                                          "Nivel educacional" 
                                                      m0_sexo 
                                      "Sexo del entrevistado" 
                                                      m0_edad 
                                      "Edad del entrevistado" </code></pre>
</div>
</div>
<p>Podemos ver que son largas o con códigos poco informativos, por lo tanto, es necesario cambiarlas por etiquetas más cortas y de fácil identificación.</p>
</section>
<section id="procesamiento-de-variables" class="level2">
<h2 class="anchored" data-anchor-id="procesamiento-de-variables">Procesamiento de variables</h2>
<p>Para el procesamiento de cada variable se seguirá el siguiente flujo de trabajo:</p>
<ol type="a">
<li>Descriptivo general</li>
<li>Recodificación: de casos perdidos y otros valores (en caso necesario)</li>
<li>Etiquetado: cambio de nombres de variables y valores (en caso necesario)</li>
<li>Otros ajustes</li>
</ol>
<p>Y se recomienda también un descriptivo final para revisar que el procesamiento de cada variable está ok.</p>
<section id="cohesión-barrial" class="level3">
<h3 class="anchored" data-anchor-id="cohesión-barrial">cohesión barrial</h3>
<p><em>a. Descriptivo</em></p>
<p>Para los descriptivos se utilizará la función <code>frq</code>, de la librería <code>sjmisc</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>t02_01)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de acuerdo: Este es el barrio ideal para mi (x) &lt;numeric&gt; 
# total N=2927 valid N=2927 mean=3.31 sd=16.51

Value |                                 Label |    N | Raw % | Valid % | Cum. %
-------------------------------------------------------------------------------
 -999 |                           No Responde |    0 |  0.00 |    0.00 |   0.00
 -888 |                               No Sabe |    1 |  0.03 |    0.03 |   0.03
 -777 |       Valor perdido por error tecnico |    0 |  0.00 |    0.00 |   0.03
 -666 | Valor perdido por encuesta incompleta |    0 |  0.00 |    0.00 |   0.03
    1 |              Totalmente en desacuerdo |  114 |  3.89 |    3.89 |   3.93
    2 |                         En desacuerdo |  413 | 14.11 |   14.11 |  18.04
    3 |        Ni de acuerdo ni en desacuerdo |  379 | 12.95 |   12.95 |  30.99
    4 |                            De acuerdo | 1599 | 54.63 |   54.63 |  85.62
    5 |                 Totalmente de acuerdo |  421 | 14.38 |   14.38 | 100.00
 &lt;NA&gt; |                                  &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>En esta variable vemos valores asociados a la opción “No contesta” (-999) y “No sabe” (-888), (-777) y (-666) que corresponde definirlos como casos perdidos (en el caso de R, como casos NA). El resto de los valores y etiquetas se encuentran en un orden correcto. Sin embargo, si queremos construir una escala, lo mejor es dejar los valores de 0 a 4</p>
<p><em>b. Recodificación</em></p>
<p>Después de revisar el libro de códigos, no hay variables en que los valores negativos representen alguna otra característica, así que podemos usar set_na</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">set_na</span>(., <span class="at">na =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">888</span>, <span class="sc">-</span><span class="dv">777</span>, <span class="sc">-</span><span class="dv">666</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>t02_01)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Grado de acuerdo: Este es el barrio ideal para mi (x) &lt;numeric&gt; 
# total N=2927 valid N=2926 mean=3.62 sd=1.02

Value |                          Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------
    1 |       Totalmente en desacuerdo |  114 |  3.89 |    3.90 |   3.90
    2 |                  En desacuerdo |  413 | 14.11 |   14.11 |  18.01
    3 | Ni de acuerdo ni en desacuerdo |  379 | 12.95 |   12.95 |  30.96
    4 |                     De acuerdo | 1599 | 54.63 |   54.65 |  85.61
    5 |          Totalmente de acuerdo |  421 | 14.38 |   14.39 | 100.00
 &lt;NA&gt; |                           &lt;NA&gt; |    1 |  0.03 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>Para reordenar las categorías volvemos a utilizar la función <code>recode</code>, de la librería <code>car</code></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>t02_01 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data<span class="sc">$</span>t02_01, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>t02_02 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data<span class="sc">$</span>t02_02, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>t02_03 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data<span class="sc">$</span>t02_03, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>t02_04 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data<span class="sc">$</span>t02_04, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><em>c - Etiquetado</em></p>
<p>Vamos a dar un nombre más sustantivo a las variables con la función <code>rename</code>, de la librería <code>dplyr</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"ideal"</span><span class="ot">=</span>t02_01, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"integracion"</span><span class="ot">=</span>t02_02, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"identificacion"</span><span class="ot">=</span>t02_03, </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"pertenencia"</span><span class="ot">=</span>t02_04)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Además de cambiar el nombre, queremos cambiar las etiquetas de las variables.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>ideal <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>ideal,<span class="at">label =</span> <span class="st">"Este barrio es ideal para mi"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>ideal)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Este barrio es ideal para mi"</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>integracion  <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>integracion, <span class="at">label =</span> <span class="st">"Me siento integrado en este barrio"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>integracion)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Me siento integrado en este barrio"</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>identificacion  <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>identificacion, <span class="at">label =</span> <span class="st">"Me identifico con la gente de este barrio"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>identificacion)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Me identifico con la gente de este barrio"</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pertenencia  <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>pertenencia, <span class="at">label =</span> <span class="st">"Me siento parte de este barrio"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>pertenencia)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Me siento parte de este barrio"</code></pre>
</div>
</div>
<p><em>Revisión final</em></p>
<p>Nuevamente un descriptivo de cada variable para confirmar que el procesamiento está ok:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>ideal)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Este barrio es ideal para mi (x) &lt;numeric&gt; 
# total N=2927 valid N=2926 mean=2.62 sd=1.02

Value |                          Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------
    0 |                              0 |  114 |  3.89 |    3.90 |   3.90
    1 |       Totalmente en desacuerdo |  413 | 14.11 |   14.11 |  18.01
    2 |                  En desacuerdo |  379 | 12.95 |   12.95 |  30.96
    3 | Ni de acuerdo ni en desacuerdo | 1599 | 54.63 |   54.65 |  85.61
    4 |                     De acuerdo |  421 | 14.38 |   14.39 | 100.00
    5 |          Totalmente de acuerdo |    0 |  0.00 |    0.00 | 100.00
 &lt;NA&gt; |                           &lt;NA&gt; |    1 |  0.03 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>integracion)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Me siento integrado en este barrio (x) &lt;numeric&gt; 
# total N=2927 valid N=2923 mean=2.57 sd=1.00

Value |                          Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------
    0 |                              0 |  109 |  3.72 |    3.73 |   3.73
    1 |       Totalmente en desacuerdo |  436 | 14.90 |   14.92 |  18.65
    2 |                  En desacuerdo |  408 | 13.94 |   13.96 |  32.60
    3 | Ni de acuerdo ni en desacuerdo | 1633 | 55.79 |   55.87 |  88.47
    4 |                     De acuerdo |  337 | 11.51 |   11.53 | 100.00
    5 |          Totalmente de acuerdo |    0 |  0.00 |    0.00 | 100.00
 &lt;NA&gt; |                           &lt;NA&gt; |    4 |  0.14 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>identificacion)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Me identifico con la gente de este barrio (x) &lt;numeric&gt; 
# total N=2927 valid N=2923 mean=2.52 sd=0.99

Value |                          Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------
    0 |                              0 |  106 |  3.62 |    3.63 |   3.63
    1 |       Totalmente en desacuerdo |  453 | 15.48 |   15.50 |  19.12
    2 |                  En desacuerdo |  460 | 15.72 |   15.74 |  34.86
    3 | Ni de acuerdo ni en desacuerdo | 1612 | 55.07 |   55.15 |  90.01
    4 |                     De acuerdo |  292 |  9.98 |    9.99 | 100.00
    5 |          Totalmente de acuerdo |    0 |  0.00 |    0.00 | 100.00
 &lt;NA&gt; |                           &lt;NA&gt; |    4 |  0.14 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>pertenencia)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Me siento parte de este barrio (x) &lt;numeric&gt; 
# total N=2927 valid N=2925 mean=2.63 sd=0.99

Value |                          Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------
    0 |                              0 |   91 |  3.11 |    3.11 |   3.11
    1 |       Totalmente en desacuerdo |  422 | 14.42 |   14.43 |  17.54
    2 |                  En desacuerdo |  362 | 12.37 |   12.38 |  29.91
    3 | Ni de acuerdo ni en desacuerdo | 1660 | 56.71 |   56.75 |  86.67
    4 |                     De acuerdo |  390 | 13.32 |   13.33 | 100.00
    5 |          Totalmente de acuerdo |    0 |  0.00 |    0.00 | 100.00
 &lt;NA&gt; |                           &lt;NA&gt; |    2 |  0.07 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>Vemos que los valores (labels) de cada categoría de las variables que recodificamos no se corresponden con el nuevo valor. Para re-etiquetar valores usamos la función <code>set_labels</code>, de la librería <code>sjlabelled</code></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>ideal <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data<span class="sc">$</span>ideal,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Totalmente en desacuerdo"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"En desacuerdo"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Ni de acuerdo ni en desacuerdo"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"De acuerdo"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Totalmente de acuerdo"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>integracion <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data<span class="sc">$</span>integracion,</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Totalmente en desacuerdo"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"En desacuerdo"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Ni de acuerdo ni en desacuerdo"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"De acuerdo"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Totalmente de acuerdo"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>identificacion <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data<span class="sc">$</span>identificacion,</span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Totalmente en desacuerdo"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"En desacuerdo"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Ni de acuerdo ni en desacuerdo"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"De acuerdo"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Totalmente de acuerdo"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pertenencia <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data<span class="sc">$</span>pertenencia,</span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Totalmente en desacuerdo"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"En desacuerdo"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Ni de acuerdo ni en desacuerdo"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"De acuerdo"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Totalmente de acuerdo"</span><span class="ot">=</span><span class="dv">4</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>y volvemos a revisar</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>ideal)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Este barrio es ideal para mi (x) &lt;numeric&gt; 
# total N=2927 valid N=2926 mean=2.62 sd=1.02

Value |                          Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------
    0 |       Totalmente en desacuerdo |  114 |  3.89 |    3.90 |   3.90
    1 |                  En desacuerdo |  413 | 14.11 |   14.11 |  18.01
    2 | Ni de acuerdo ni en desacuerdo |  379 | 12.95 |   12.95 |  30.96
    3 |                     De acuerdo | 1599 | 54.63 |   54.65 |  85.61
    4 |          Totalmente de acuerdo |  421 | 14.38 |   14.39 | 100.00
 &lt;NA&gt; |                           &lt;NA&gt; |    1 |  0.03 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>pertenencia)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Me siento parte de este barrio (x) &lt;numeric&gt; 
# total N=2927 valid N=2925 mean=2.63 sd=0.99

Value |                          Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------
    0 |       Totalmente en desacuerdo |   91 |  3.11 |    3.11 |   3.11
    1 |                  En desacuerdo |  422 | 14.42 |   14.43 |  17.54
    2 | Ni de acuerdo ni en desacuerdo |  362 | 12.37 |   12.38 |  29.91
    3 |                     De acuerdo | 1660 | 56.71 |   56.75 |  86.67
    4 |          Totalmente de acuerdo |  390 | 13.32 |   13.33 | 100.00
 &lt;NA&gt; |                           &lt;NA&gt; |    2 |  0.07 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<section id="educación" class="level4">
<h4 class="anchored" data-anchor-id="educación">4.2. Educación</h4>
<ul>
<li>[<code>m01</code>] = Nivel de estudios alcanzado - Entrevistado</li>
</ul>
<p><em>a. Descriptivo</em></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m01)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Nivel educacional (x) &lt;numeric&gt; 
# total N=2927 valid N=2925 mean=5.26 sd=2.20

Value |                                       Label |   N | Raw % | Valid % | Cum. %
------------------------------------------------------------------------------------
    1 |                                Sin estudios |  37 |  1.26 |    1.26 |   1.26
    2 |  Educacion Basica o Preparatoria incompleta | 322 | 11.00 |   11.01 |  12.27
    3 |    Educacion Basica o Preparatoria completa | 297 | 10.15 |   10.15 |  22.43
    4 |    Educacion Media o Humanidades incompleta | 394 | 13.46 |   13.47 |  35.90
    5 |      Educacion Media o Humanidades completa | 857 | 29.28 |   29.30 |  65.20
    6 |                 Tecnica Superior incompleta | 102 |  3.48 |    3.49 |  68.68
    7 |                   Tecnica Superior completa | 381 | 13.02 |   13.03 |  81.71
    8 |                    Universitaria incompleta | 186 |  6.35 |    6.36 |  88.07
    9 |                      Universitaria completa | 303 | 10.35 |   10.36 |  98.43
   10 | Estudios de posgrado (magister o doctorado) |  46 |  1.57 |    1.57 | 100.00
 &lt;NA&gt; |                                        &lt;NA&gt; |   2 |  0.07 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
<p>Esta vez la vamos a dejar así</p>
</section>
</section>
<section id="sexo" class="level3">
<h3 class="anchored" data-anchor-id="sexo">4.3. Sexo</h3>
<ul>
<li>[<code>m0_sexo</code>] = SEXO Sexo</li>
</ul>
<p><em>a. Descriptivo</em></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m0_sexo)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Sexo del entrevistado (x) &lt;numeric&gt; 
# total N=2927 valid N=2927 mean=1.60 sd=0.49

Value |  Label |    N | Raw % | Valid % | Cum. %
------------------------------------------------
    1 | Hombre | 1163 | 39.73 |   39.73 |  39.73
    2 |  Mujer | 1764 | 60.27 |   60.27 | 100.00
 &lt;NA&gt; |   &lt;NA&gt; |    0 |  0.00 |    &lt;NA&gt; |   &lt;NA&gt;</code></pre>
</div>
</div>
</section>
<section id="edad" class="level3">
<h3 class="anchored" data-anchor-id="edad">4.4 Edad</h3>
<ul>
<li>[<code>m0_edad</code>] = EDAD Edad.</li>
</ul>
<p><em>a. Descriptivo</em></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data<span class="sc">$</span>m0_edad)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  18.00   33.00   46.00   46.09   58.00   88.00 </code></pre>
</div>
</div>
</section>
</section>
<section id="generación-de-base-de-datos-procesada-para-el-análisis" class="level2">
<h2 class="anchored" data-anchor-id="generación-de-base-de-datos-procesada-para-el-análisis">5. Generación de base de datos procesada para el análisis</h2>
<p>Antes de guardar la base procesada, revisamos nuevamente todas las variables con una tabla descriptiva general mediante la función <code>stargazer</code> (de la librería homónima)</p>
<p>Primero vamos a reformatear el objeto proc_data como base de datos (as.data.frame), paso necesario para que sea reconocido como tal por <code>stargazer</code></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(proc_data)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(proc_data, <span class="at">type=</span><span class="st">"text"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
============================================
Statistic        N    Mean  St. Dev. Min Max
--------------------------------------------
ideal          2,926 2.615   1.020    0   4 
integracion    2,923 2.566   0.999    0   4 
identificacion 2,923 2.524   0.988    0   4 
pertenencia    2,925 2.628   0.988    0   4 
m01            2,925 5.261   2.202    1  10 
m0_sexo        2,927 1.603   0.489    1   2 
m0_edad        2,927 46.091  15.287  18  88 
--------------------------------------------</code></pre>
</div>
</div>
<ul>
<li>Guardar base de datos procesada: en carpeta local <span class="sidenote">La ruta hacia su carpeta local si está trabajando en windows debería ser algo como “C:/Users/Lenovo/Clases/y aquí nombre del archivo a grabar</span></li>
</ul>
<p>El comando para guardar es <code>save</code>:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_data,<span class="at">file =</span> <span class="st">"[ruta hacia carpeta local en su computador]/ELSOC_ess_merit2016.RData"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>En este caso, seguimos una estructura de carpetas de datos, separando en una carpeta los datos originales, y en otra (proc) los datos procesados:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(proc_data,<span class="at">file =</span> <span class="st">"input/data/elsoc2016_proc.RData"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="análisis" class="level1">
<h1>Análisis</h1>
<p>Una vez que tenemos recodificadas nuestras variables en el archivo de preparación y logramos exportar la base de datos procesada en la carpeta input/data, abrimos un documento de quarto (.qmd) para realizar el análisis.</p>
<p>Al trabajar con quarto (y al intentar renderizar), el documento leerá todos lo que esté escrito en el documento desde 0, por lo que es necesario <strong>siempre</strong> cargar de nuevo los paquetes y bases de datos.</p>
<p>Primero cargamos los paquetes:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, sjmisc, car, sjlabelled, stargazer, haven, sjPlot, ggplot2, psych, kableExtra, corrplot)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>y la base procesada</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"input/data/elsoc2016_proc.RData"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="análisis-descriptivo" class="level3">
<h3 class="anchored" data-anchor-id="análisis-descriptivo">Análisis descriptivo</h3>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>))<span class="sc">%&gt;%</span> <span class="co"># Selecciona estadísticos</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">kable</span>(.,<span class="st">"markdown"</span>) <span class="co"># Esto es para que se vea bien en quarto</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-sjmisc" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sjmisc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabla&nbsp;1: Descriptivos
</figcaption>
<div aria-describedby="tbl-sjmisc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 2%">
<col style="width: 14%">
<col style="width: 39%">
<col style="width: 4%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">var</th>
<th style="text-align: left;">label</th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">NA.prc</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: left;">range</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">ideal</td>
<td style="text-align: left;">Este barrio es ideal para mi</td>
<td style="text-align: right;">2926</td>
<td style="text-align: right;">0.0341647</td>
<td style="text-align: right;">2.615174</td>
<td style="text-align: right;">1.0202541</td>
<td style="text-align: left;">4 (0-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">integracion</td>
<td style="text-align: left;">Me siento integrado en este barrio</td>
<td style="text-align: right;">2923</td>
<td style="text-align: right;">0.1366587</td>
<td style="text-align: right;">2.565515</td>
<td style="text-align: right;">0.9993502</td>
<td style="text-align: left;">4 (0-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">identificacion</td>
<td style="text-align: left;">Me identifico con la gente de este barrio</td>
<td style="text-align: right;">2923</td>
<td style="text-align: right;">0.1366587</td>
<td style="text-align: right;">2.523777</td>
<td style="text-align: right;">0.9884856</td>
<td style="text-align: left;">4 (0-4)</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">pertenencia</td>
<td style="text-align: left;">Me siento parte de este barrio</td>
<td style="text-align: right;">2925</td>
<td style="text-align: right;">0.0683293</td>
<td style="text-align: right;">2.627692</td>
<td style="text-align: right;">0.9878809</td>
<td style="text-align: left;">4 (0-4)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">m01</td>
<td style="text-align: left;">Nivel educacional</td>
<td style="text-align: right;">2925</td>
<td style="text-align: right;">0.0683293</td>
<td style="text-align: right;">5.260513</td>
<td style="text-align: right;">2.2015019</td>
<td style="text-align: left;">9 (1-10)</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">m0_sexo</td>
<td style="text-align: left;">Sexo del entrevistado</td>
<td style="text-align: right;">2927</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">1.602665</td>
<td style="text-align: right;">0.4894300</td>
<td style="text-align: left;">1 (1-2)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">m0_edad</td>
<td style="text-align: left;">Edad del entrevistado</td>
<td style="text-align: right;">2927</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">46.090878</td>
<td style="text-align: right;">15.2867983</td>
<td style="text-align: left;">70 (18-88)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>En la <a href="#tbl-sjmisc" class="quarto-xref">Tabla&nbsp;1</a> podemos observar los descriptivos generales de la base de datos procesada.</p>
<p>Y si queremos visualizar algo más:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(ideal, integracion, identificacion, pertenencia) <span class="sc">%&gt;%</span> </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  sjPlot<span class="sc">::</span><span class="fu">plot_stackfrq</span>()<span class="sc">+</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-descriptivos" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-descriptivos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="resumen-content_files/figure-html/fig-descriptivos-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-descriptivos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Frecuencias Cohesión barrial
</figcaption>
</figure>
</div>
</div>
</div>
<p>En la <a href="#fig-descriptivos" class="quarto-xref">Figura&nbsp;1</a> podemos ver la distribución de las variables de cohesión barrial, donde se puede observar que más del 65% de la muestra está de acuerdo o totalmente de acuerdo con las afirmaciones indicadas.</p>
</section>
<section id="asociación-de-variables" class="level3">
<h3 class="anchored" data-anchor-id="asociación-de-variables">Asociación de variables</h3>
<p>Podemos ver la asociación de todas las variables, como lo muestra la <strong>?@cor-complete</strong></p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(proc_data, <span class="at">use =</span> <span class="st">"complete.obs"</span>) <span class="co"># Usar solo casos con observaciones completas</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(M)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="resumen-content_files/figure-html/cor-complete-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Cohesión variables elsoc 2016</figcaption>
</figure>
</div>
</div>
</div>
<p>o podemos ver específicamente la asociación de las variables de cohesión barrial</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">cor</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data, ideal, integracion, identificacion, pertenencia), <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(M2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-cor-cohesion" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cor-cohesion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="resumen-content_files/figure-html/fig-cor-cohesion-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cor-cohesion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Correlación Cohesión barrial
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-cor-cohesion" class="quarto-xref">Figura&nbsp;2</a> muestra que la asociación de las cuatro variables de cohesión barrial es alta y positiva, según Cohen (1998). En general el tamaño de efecto varía entre 0.58 la más baja y 0.69 la más alta.</p>
</section>
<section id="construcción-de-escala" class="level3">
<h3 class="anchored" data-anchor-id="construcción-de-escala">Construcción de escala</h3>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data, ideal, integracion, identificacion, pertenencia))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Reliability analysis   
Call: psych::alpha(x = dplyr::select(proc_data, ideal, integracion, 
    identificacion, pertenencia))

  raw_alpha std.alpha G6(smc) average_r S/N    ase mean   sd median_r
      0.87      0.87    0.84      0.63 6.8 0.0039  2.6 0.85     0.62

    95% confidence boundaries 
         lower alpha upper
Feldt     0.86  0.87  0.88
Duhachek  0.86  0.87  0.88

 Reliability if an item is dropped:
               raw_alpha std.alpha G6(smc) average_r S/N alpha se   var.r med.r
ideal               0.85      0.85    0.80      0.66 5.8   0.0047 0.00086  0.65
integracion         0.84      0.84    0.78      0.63 5.1   0.0053 0.00299  0.61
identificacion      0.83      0.83    0.76      0.62 4.9   0.0055 0.00015  0.61
pertenencia         0.83      0.83    0.76      0.62 4.8   0.0055 0.00121  0.61

 Item statistics 
                  n raw.r std.r r.cor r.drop mean   sd
ideal          2926  0.83  0.83  0.73   0.69  2.6 1.02
integracion    2923  0.85  0.85  0.78   0.73  2.6 1.00
identificacion 2923  0.86  0.86  0.80   0.74  2.5 0.99
pertenencia    2925  0.86  0.86  0.80   0.75  2.6 0.99

Non missing response frequency for each item
                  0    1    2    3    4 miss
ideal          0.04 0.14 0.13 0.55 0.14    0
integracion    0.04 0.15 0.14 0.56 0.12    0
identificacion 0.04 0.15 0.16 0.55 0.10    0
pertenencia    0.03 0.14 0.12 0.57 0.13    0</code></pre>
</div>
</div>
<p>La consistencia interna de una posible escala entre estos cuatro ítems es de 0.87, lo que representa una alta consistencia interna. Si quitaramos alguno de estos ítems la consistencia interna solo bajaría, así que podemos construir una escala con los cuatro ítems.</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cohesion_barrial =</span> <span class="fu">sum</span>(ideal, integracion, identificacion, pertenencia))</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data<span class="sc">$</span>cohesion_barrial)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
   0.00    8.00   12.00   10.33   12.00   16.00      10 </code></pre>
</div>
</div>
<p>y la podemos visualizar en un gráfico:</p>
<div class="cell">
<details open="" class="code-fold">
<summary>Código</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proc_data, <span class="fu">aes</span>(<span class="at">x =</span> cohesion_barrial)) <span class="sc">+</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.6</span>, <span class="at">colour=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"yellow"</span>) <span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Cohesión barrial"</span>) <span class="sc">+</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite values (`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-plot-cohesion" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot-cohesion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="resumen-content_files/figure-html/fig-plot-cohesion-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot-cohesion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Histograma Cohesión barrial
</figcaption>
</figure>
</div>
</div>
</div>
<p>La <a href="#fig-plot-cohesion" class="quarto-xref">Figura&nbsp;3</a> muestra la distribución de la nueva escala de Cohesión Barrial que construimos. En general, la mayor concentración de casos está en la categoría 12 y que sumado a un promedio de 10.33 según los descriptivos anteriores, podríamos afirmar que la cohesión barrial en Chile es alta.</p>
</section>
</section>
<section id="subir-a-github" class="level1">
<h1>Subir a github</h1>
<p>Una vez que tenemos nuestro cambios hechos, vamos a Github desktop y seguimos los siguientes pasos:</p>
<p><img src="../files/img/upload-github.png" class="img-fluid"></p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/R-analisis-datos\.netlify\.app");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Ejecutar el código</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb61" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Resumen"</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "R data analisis"</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="an">linktitle:</span><span class="co"> "Resumen"</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> "2024-05-07"</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> es</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="fu"># Presentación</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivo de la práctica</span></span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>Como siempre, estas guías no apuntan a ser un **paso a paso** de lo que se debe hacer, sino que son un ejemplo concreto de cómo hacer ciertos tipos de análisis con un conjunto de datos determinados. Los procedimientos de limpieza van a depender siempre del conjunto de datos que utilicemos en nuestras investigaciones y el proceso de análisis va a depender de nuestros objetivos de investigación, en relación con las variables e hipótesis que queramos demostrar.</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>El desarrollo de esta guía tiene por objetivo revisar todos los contenidos trabajados hasta este momento del curso (07/05/2024). En términos generales, es un resumen de las cosas esenciales de los 7 prácticos anteriores como limpieza y preparación de datos, análisis descriptivo, bivariado y visualización de datos en Quarto y subida a github y visualización de github pages.</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>En concreto, un ejemplo del resultado final de un trabajo se debería poder visualizar así en un <span class="co">[</span><span class="ot">repositorio de github</span><span class="co">](https://github.com/Kevin-carrasco/ipo)</span> y en <span class="co">[</span><span class="ot">Github pages</span><span class="co">](https://kevin-carrasco.github.io/ipo/trabajo.html)</span></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>Por temas de orden y reproducibilidad, en este curso hemos separado en **dos momentos** el trabajo con datos, y dos archivos de código correspondientes:</span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Preparación** corresponde a lo que se conoce generalmente como "limpieza", es decir, realizar las modificaciones necesarias para poder efectuar los análisis. Estas modificaciones previas al análisis son necesarias ya que los datos originales con los que se va a trabajar en general no vienen perfectamente adaptados a los análisis que se quieren hacer. Por lo tanto, en cuanto a datos también hacemos la distinción entre datos originales y datos preparados (o procesados). Este código de análisis lo podemos encontrar en la carpeta <span class="co">[</span><span class="ot">procesamiento</span><span class="co">](https://github.com/Kevin-carrasco/ipo/tree/main/processing)</span> del repositorio</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>**Análisis**: se relaciona tanto con análisis descriptivos asociados a las preguntas de investigación y como también modelamiento de datos para contrastar hipótesis de investigación. En este curso lo esencial es visualizar el análisis a través de quarto, por lo que el <span class="co">[</span><span class="ot">documento .qmd</span><span class="co">](https://github.com/Kevin-carrasco/ipo/blob/main/trabajo.qmd)</span> debería estar en el inicio del repositorio (junto al Rproject). Este documento se debe renderizar y obtenemos un <span class="co">[</span><span class="ot">archivo .html</span><span class="co">](https://github.com/Kevin-carrasco/ipo/blob/main/trabajo.html)</span> que se podría visualizar a través de github pages en, por ejemplo, el link: <span class="co">[</span><span class="ot">https://kevin-carrasco.github.io/ipo/trabajo.html</span><span class="co">](https://kevin-carrasco.github.io/ipo/trabajo.html)</span>. Dónde:</span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a><span class="al">![](../files/img/url-pages.png)</span></span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>**Vamos paso a paso**</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a><span class="fu"># Preparación</span></span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a><span class="fu">## Los procesos de preparación y análisis vinculados a datos y resultados se presentan en el siguiente esquema:{#flujo}</span></span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a><span class="al">![](images/produccion.png)</span></span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a>Tanto la preparación como el análisis (que son parte del concepto más general de procesamiento) quedan registrados cada uno en un _archivo de código_.</span>
<span id="cb61-36"><a href="#cb61-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-37"><a href="#cb61-37" aria-hidden="true" tabindex="-1"></a>&lt;span class="sidenote"&gt;**Archivo de código R**: archivo con extensión .R donde se almacena el código de análisis. Para generarlo desde RStudio: _File &gt; New File &gt; R Script_ (o ctrl+shift+N), y para grabarlo  _File &gt; Save (o ctrl+s)_, y darle nombre la primera vez (recordar: sin tilde ni ñ, y evitar espacios) &lt;/span&gt;</span>
<span id="cb61-38"><a href="#cb61-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-39"><a href="#cb61-39" aria-hidden="true" tabindex="-1"></a>El documento de **código de preparación** posee 5 partes, más una sección de identificación inicial:</span>
<span id="cb61-40"><a href="#cb61-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-41"><a href="#cb61-41" aria-hidden="true" tabindex="-1"></a><span class="ss">0. </span>Identificación y descripción general: Título, autor(es), fecha, información breve sobre el contenido del documento</span>
<span id="cb61-42"><a href="#cb61-42" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>Librerías: cargar librerías a utilizar</span>
<span id="cb61-43"><a href="#cb61-43" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>Datos: carga de datos</span>
<span id="cb61-44"><a href="#cb61-44" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>Selección de variables a utilizar</span>
<span id="cb61-45"><a href="#cb61-45" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>Procesamiento de variables: en este punto, por cada variable se realiza lo siguiente:</span>
<span id="cb61-46"><a href="#cb61-46" aria-hidden="true" tabindex="-1"></a>    a. Descriptivo básico</span>
<span id="cb61-47"><a href="#cb61-47" aria-hidden="true" tabindex="-1"></a>    b. Recodificación: datos perdidos y valores (en caso de ser necesario)</span>
<span id="cb61-48"><a href="#cb61-48" aria-hidden="true" tabindex="-1"></a>    c. Etiquetamiento: de variable y valores (en caso de ser necesario)</span>
<span id="cb61-49"><a href="#cb61-49" aria-hidden="true" tabindex="-1"></a>    e. Otros ajustes</span>
<span id="cb61-50"><a href="#cb61-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-51"><a href="#cb61-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-52"><a href="#cb61-52" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>Generación de base de datos preparada para el análisis.</span>
<span id="cb61-53"><a href="#cb61-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-54"><a href="#cb61-54" aria-hidden="true" tabindex="-1"></a>&lt;div class="alert alert-info"&gt;</span>
<span id="cb61-55"><a href="#cb61-55" aria-hidden="true" tabindex="-1"></a>**De rutas, estructura de carpetas y otros **</span>
<span id="cb61-56"><a href="#cb61-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-57"><a href="#cb61-57" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Encontrando la ruta a carpeta local**: lo más fácil es crear la carpeta donde se desean guardar los datos desde el administrador de archivos del computador. Luego, posicionarse con el cursor sobre la carpeta y seleccionar "Propiedades", en la ventana emergente debería aparecer la ruta hacia la carpeta en "Ubicación". Copiar esa ruta y agregar al final el nombre de la carpeta (separada por slash)</span>
<span id="cb61-58"><a href="#cb61-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-59"><a href="#cb61-59" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Sobre los "slashes" (`\` o `/`)**: en la ruta las carpetas y el archivo final aparecen separados por slashes, que según el sistema utilizado pueden ser _slash_ (`/`) o _backslash_ (`\`). En R por defecto se usa _slash_, pero en Windows _backslash_, por lo que si se usa Windows hay que reemplazarlos por _backslash_ o también puede ser por un doble _slash_ (<span class="in">`//`</span>).</span>
<span id="cb61-60"><a href="#cb61-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-61"><a href="#cb61-61" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Por temas de compatibilidad general, en las rutas se recomienda evitar tildes, eñes, espacios, mayúsculas y guiones bajos (_).</span>
<span id="cb61-62"><a href="#cb61-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-63"><a href="#cb61-63" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Estructura de carpetas**: para mantener el orden se sugiere seguir un protocolo de estructura de carpetas de proyecto, para lo que recomendamos el protocolo [IPO](https://lisa-coes.com/ipo-protocol/), y que se adapta al flujo de trabajo presentado anteriormente. Básicamente son tres carpetas: **input**, **procesamiento**, **output**. En la carpeta input crear la subcarpeta data-orig para guardar datos originales, y data-proc para los procesados. En procesamiento se guardan los archivos de código y en output las tablas y los gráficos.</span>
<span id="cb61-64"><a href="#cb61-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-65"><a href="#cb61-65" aria-hidden="true" tabindex="-1"></a><span class="al">![](../files/img/ipo-hex.png)</span></span>
<span id="cb61-66"><a href="#cb61-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-67"><a href="#cb61-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-68"><a href="#cb61-68" aria-hidden="true" tabindex="-1"></a>&lt;div&gt;</span>
<span id="cb61-69"><a href="#cb61-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-70"><a href="#cb61-70" aria-hidden="true" tabindex="-1"></a>Nuestras carpetas se deberían ver así:</span>
<span id="cb61-71"><a href="#cb61-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-72"><a href="#cb61-72" aria-hidden="true" tabindex="-1"></a><span class="al">![](../files/img/carpetas.png)</span></span>
<span id="cb61-73"><a href="#cb61-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-74"><a href="#cb61-74" aria-hidden="true" tabindex="-1"></a>Donde lo primero que debemos hacer, siempre, es abrir el Rproject (.Rproj) para comenzar nuestro trabajo.</span>
<span id="cb61-75"><a href="#cb61-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-76"><a href="#cb61-76" aria-hidden="true" tabindex="-1"></a><span class="fu">## Antecedentes de los datos a utilizar</span></span>
<span id="cb61-77"><a href="#cb61-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-78"><a href="#cb61-78" aria-hidden="true" tabindex="-1"></a>Cohesión barrial con elsoc 2016</span>
<span id="cb61-79"><a href="#cb61-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-80"><a href="#cb61-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-81"><a href="#cb61-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-82"><a href="#cb61-82" aria-hidden="true" tabindex="-1"></a><span class="fu">## 1. Librerías principales (de R) a utilizar en el análisis{#librerias}</span></span>
<span id="cb61-83"><a href="#cb61-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-86"><a href="#cb61-86" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-87"><a href="#cb61-87" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, sjmisc, car, sjlabelled, stargazer, haven, sjPlot, ggplot2, psych)</span>
<span id="cb61-88"><a href="#cb61-88" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-89"><a href="#cb61-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-90"><a href="#cb61-90" aria-hidden="true" tabindex="-1"></a><span class="fu">## 2. Cargar base de datos</span></span>
<span id="cb61-91"><a href="#cb61-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-92"><a href="#cb61-92" aria-hidden="true" tabindex="-1"></a>**Ajustar espacio de trabajo**</span>
<span id="cb61-93"><a href="#cb61-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-94"><a href="#cb61-94" aria-hidden="true" tabindex="-1"></a>Previo a la carga de nuestra base de datos, se recomienda ejecutar los siguientes comandos:</span>
<span id="cb61-95"><a href="#cb61-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-98"><a href="#cb61-98" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-99"><a href="#cb61-99" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())       <span class="co"># borrar todos los objetos en el espacio de trabajo</span></span>
<span id="cb61-100"><a href="#cb61-100" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">scipen=</span><span class="dv">999</span>) <span class="co"># valores sin notación científica</span></span>
<span id="cb61-101"><a href="#cb61-101" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-102"><a href="#cb61-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-103"><a href="#cb61-103" aria-hidden="true" tabindex="-1"></a>La función <span class="in">`rm(list=ls())`</span> permite comenzar con un espacio de trabajo (environment) vacío y sin otros objetos. Así también, la función <span class="in">`options(scipen=999)`</span> desactiva la notación científica, es decir, veremos los valores numéricos con todos sus decimales.</span>
<span id="cb61-104"><a href="#cb61-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-105"><a href="#cb61-105" aria-hidden="true" tabindex="-1"></a>**Datos**</span>
<span id="cb61-106"><a href="#cb61-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-107"><a href="#cb61-107" aria-hidden="true" tabindex="-1"></a>Las bases de datos se pueden cargar de un archivo local o en línea. Para este caso utilizaremos un archivo en línea que viene en formato RData: **elsoc.RData**. &lt;span class="sidenote"&gt;**Abrir bases de datos en otros formatos**: Los formatos mas comunes en que se almacenan las bases de datos son .dta (Stata),  .sav (Spss) y RData (R). Para abrir desde R utlilizamos la librería <span class="in">`haven`</span> y sus funciones read_dta y read_sav según corresponda. Ej: <span class="in">`datos &lt;- read_dta("base_casen.dta")`</span>. Recordar antes instalar/cargar la librería: <span class="in">`pacman::p_load(haven)`</span>   &lt;/span&gt;</span>
<span id="cb61-108"><a href="#cb61-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-111"><a href="#cb61-111" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-112"><a href="#cb61-112" aria-hidden="true" tabindex="-1"></a><span class="co">#cargamos la base de datos desde internet</span></span>
<span id="cb61-113"><a href="#cb61-113" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://dataverse.harvard.edu/api/access/datafile/7245118"</span>)) <span class="co">#Cargar base de datos</span></span>
<span id="cb61-114"><a href="#cb61-114" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-115"><a href="#cb61-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-116"><a href="#cb61-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-117"><a href="#cb61-117" aria-hidden="true" tabindex="-1"></a>Realizamos un chequeo básico de la lectura de datos: nombres de las variables y tamaño de la base en términos de casos y variables (en este ejemplo, <span class="in">`r dim(elsoc_long_2016_2022.2)`</span> ).</span>
<span id="cb61-118"><a href="#cb61-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-121"><a href="#cb61-121" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-122"><a href="#cb61-122" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(elsoc_long_2016_2022<span class="fl">.2</span>) <span class="co"># dimension de la base</span></span>
<span id="cb61-123"><a href="#cb61-123" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-124"><a href="#cb61-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-125"><a href="#cb61-125" aria-hidden="true" tabindex="-1"></a><span class="fu">## 3. Selección de variables a utilizar</span></span>
<span id="cb61-126"><a href="#cb61-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-127"><a href="#cb61-127" aria-hidden="true" tabindex="-1"></a>Este paso consiste en crear un subset reducido de datos que contenga solo las variables de interés. Para ello lo más fácil es revisar el libro de códigos de cada base de datos. Además filtramos por la ola 1 para trabajar solo con datos del 2016.</span>
<span id="cb61-128"><a href="#cb61-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-131"><a href="#cb61-131" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-132"><a href="#cb61-132" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> elsoc_long_2016_2022<span class="fl">.2</span> <span class="sc">%&gt;%</span> <span class="fu">filter</span>(ola<span class="sc">==</span><span class="st">"1"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb61-133"><a href="#cb61-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(t02_01, <span class="co"># Este barrio es ideal para mi</span></span>
<span id="cb61-134"><a href="#cb61-134" aria-hidden="true" tabindex="-1"></a>         t02_02, <span class="co"># Me siento incluido en este barrio</span></span>
<span id="cb61-135"><a href="#cb61-135" aria-hidden="true" tabindex="-1"></a>         t02_03, <span class="co"># Me identifico con la gente de este barrio</span></span>
<span id="cb61-136"><a href="#cb61-136" aria-hidden="true" tabindex="-1"></a>         t02_04, <span class="co"># Este barrio es parte de mi</span></span>
<span id="cb61-137"><a href="#cb61-137" aria-hidden="true" tabindex="-1"></a>         m01,<span class="co"># nivel educacional</span></span>
<span id="cb61-138"><a href="#cb61-138" aria-hidden="true" tabindex="-1"></a>         m0_sexo,<span class="co"># sexo</span></span>
<span id="cb61-139"><a href="#cb61-139" aria-hidden="true" tabindex="-1"></a>         m0_edad<span class="co"># edad</span></span>
<span id="cb61-140"><a href="#cb61-140" aria-hidden="true" tabindex="-1"></a>         )</span>
<span id="cb61-141"><a href="#cb61-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-142"><a href="#cb61-142" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobar</span></span>
<span id="cb61-143"><a href="#cb61-143" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(proc_data)</span>
<span id="cb61-144"><a href="#cb61-144" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-145"><a href="#cb61-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-146"><a href="#cb61-146" aria-hidden="true" tabindex="-1"></a>Mediante el comando <span class="in">`get_label`</span> obtenemos el atributo label de las variables.</span>
<span id="cb61-147"><a href="#cb61-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-150"><a href="#cb61-150" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-151"><a href="#cb61-151" aria-hidden="true" tabindex="-1"></a>sjlabelled<span class="sc">::</span><span class="fu">get_label</span>(proc_data)</span>
<span id="cb61-152"><a href="#cb61-152" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-153"><a href="#cb61-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-154"><a href="#cb61-154" aria-hidden="true" tabindex="-1"></a>Podemos ver que son largas o con códigos poco informativos, por lo tanto, es necesario cambiarlas por etiquetas más cortas y de fácil identificación.</span>
<span id="cb61-155"><a href="#cb61-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-156"><a href="#cb61-156" aria-hidden="true" tabindex="-1"></a><span class="fu">## Procesamiento de variables</span></span>
<span id="cb61-157"><a href="#cb61-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-158"><a href="#cb61-158" aria-hidden="true" tabindex="-1"></a>Para el procesamiento de cada variable se seguirá el siguiente flujo de trabajo:</span>
<span id="cb61-159"><a href="#cb61-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-160"><a href="#cb61-160" aria-hidden="true" tabindex="-1"></a>a. Descriptivo general</span>
<span id="cb61-161"><a href="#cb61-161" aria-hidden="true" tabindex="-1"></a>b. Recodificación: de casos perdidos y otros valores (en caso necesario)</span>
<span id="cb61-162"><a href="#cb61-162" aria-hidden="true" tabindex="-1"></a>c. Etiquetado: cambio de nombres de variables y valores (en caso necesario)</span>
<span id="cb61-163"><a href="#cb61-163" aria-hidden="true" tabindex="-1"></a>d. Otros ajustes</span>
<span id="cb61-164"><a href="#cb61-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-165"><a href="#cb61-165" aria-hidden="true" tabindex="-1"></a>Y se recomienda también un descriptivo final para revisar que el procesamiento de cada variable está ok.</span>
<span id="cb61-166"><a href="#cb61-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-167"><a href="#cb61-167" aria-hidden="true" tabindex="-1"></a><span class="fu">### cohesión barrial</span></span>
<span id="cb61-168"><a href="#cb61-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-169"><a href="#cb61-169" aria-hidden="true" tabindex="-1"></a>_a. Descriptivo_</span>
<span id="cb61-170"><a href="#cb61-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-171"><a href="#cb61-171" aria-hidden="true" tabindex="-1"></a>Para los descriptivos se utilizará la función <span class="in">`frq`</span>, de la librería <span class="in">`sjmisc`</span>:</span>
<span id="cb61-172"><a href="#cb61-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-175"><a href="#cb61-175" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-176"><a href="#cb61-176" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>t02_01)</span>
<span id="cb61-177"><a href="#cb61-177" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-178"><a href="#cb61-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-179"><a href="#cb61-179" aria-hidden="true" tabindex="-1"></a>En esta variable vemos valores asociados a la opción "No contesta" (-999) y "No sabe" (-888), (-777) y (-666) que corresponde definirlos como casos perdidos (en el caso de R, como casos NA). El resto de los valores y etiquetas se encuentran en un orden correcto. Sin embargo, si queremos construir una escala, lo mejor es dejar los valores de 0 a 4</span>
<span id="cb61-180"><a href="#cb61-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-181"><a href="#cb61-181" aria-hidden="true" tabindex="-1"></a>_b. Recodificación_</span>
<span id="cb61-182"><a href="#cb61-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-183"><a href="#cb61-183" aria-hidden="true" tabindex="-1"></a>Después de revisar el libro de códigos, no hay variables en que los valores negativos representen alguna otra característica, así que podemos usar set_na</span>
<span id="cb61-184"><a href="#cb61-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-185"><a href="#cb61-185" aria-hidden="true" tabindex="-1"></a><span class="in">```{r }</span></span>
<span id="cb61-186"><a href="#cb61-186" aria-hidden="true" tabindex="-1"></a><span class="in">proc_data &lt;- proc_data %&gt;% set_na(., na = c(-999, -888, -777, -666))</span></span>
<span id="cb61-187"><a href="#cb61-187" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-188"><a href="#cb61-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-191"><a href="#cb61-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-192"><a href="#cb61-192" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>t02_01)</span>
<span id="cb61-193"><a href="#cb61-193" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-194"><a href="#cb61-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-195"><a href="#cb61-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-196"><a href="#cb61-196" aria-hidden="true" tabindex="-1"></a>Para reordenar las categorías volvemos a utilizar la función <span class="in">`recode`</span>, de la librería <span class="in">`car`</span></span>
<span id="cb61-197"><a href="#cb61-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-200"><a href="#cb61-200" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-201"><a href="#cb61-201" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>t02_01 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data<span class="sc">$</span>t02_01, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb61-202"><a href="#cb61-202" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>t02_02 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data<span class="sc">$</span>t02_02, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb61-203"><a href="#cb61-203" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>t02_03 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data<span class="sc">$</span>t02_03, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb61-204"><a href="#cb61-204" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>t02_04 <span class="ot">&lt;-</span> <span class="fu">recode</span>(proc_data<span class="sc">$</span>t02_04, <span class="st">"1=0; 2=1; 3=2; 4=3; 5=4"</span>)</span>
<span id="cb61-205"><a href="#cb61-205" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-206"><a href="#cb61-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-207"><a href="#cb61-207" aria-hidden="true" tabindex="-1"></a>_c - Etiquetado_</span>
<span id="cb61-208"><a href="#cb61-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-209"><a href="#cb61-209" aria-hidden="true" tabindex="-1"></a>Vamos a dar un nombre más sustantivo a las variables con la función <span class="in">`rename`</span>, de la librería <span class="in">`dplyr`</span>:</span>
<span id="cb61-210"><a href="#cb61-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-213"><a href="#cb61-213" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-214"><a href="#cb61-214" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="st">"ideal"</span><span class="ot">=</span>t02_01, </span>
<span id="cb61-215"><a href="#cb61-215" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"integracion"</span><span class="ot">=</span>t02_02, </span>
<span id="cb61-216"><a href="#cb61-216" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"identificacion"</span><span class="ot">=</span>t02_03, </span>
<span id="cb61-217"><a href="#cb61-217" aria-hidden="true" tabindex="-1"></a>                                  <span class="st">"pertenencia"</span><span class="ot">=</span>t02_04)</span>
<span id="cb61-218"><a href="#cb61-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-219"><a href="#cb61-219" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-220"><a href="#cb61-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-221"><a href="#cb61-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-222"><a href="#cb61-222" aria-hidden="true" tabindex="-1"></a>Además de cambiar el nombre, queremos cambiar las etiquetas de las variables.</span>
<span id="cb61-223"><a href="#cb61-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-226"><a href="#cb61-226" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-227"><a href="#cb61-227" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>ideal <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>ideal,<span class="at">label =</span> <span class="st">"Este barrio es ideal para mi"</span>)</span>
<span id="cb61-228"><a href="#cb61-228" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>ideal)</span>
<span id="cb61-229"><a href="#cb61-229" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-230"><a href="#cb61-230" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>integracion  <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>integracion, <span class="at">label =</span> <span class="st">"Me siento integrado en este barrio"</span>)</span>
<span id="cb61-231"><a href="#cb61-231" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>integracion)</span>
<span id="cb61-232"><a href="#cb61-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-233"><a href="#cb61-233" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>identificacion  <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>identificacion, <span class="at">label =</span> <span class="st">"Me identifico con la gente de este barrio"</span>)</span>
<span id="cb61-234"><a href="#cb61-234" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>identificacion)</span>
<span id="cb61-235"><a href="#cb61-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-236"><a href="#cb61-236" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pertenencia  <span class="ot">&lt;-</span> <span class="fu">set_label</span>(<span class="at">x =</span> proc_data<span class="sc">$</span>pertenencia, <span class="at">label =</span> <span class="st">"Me siento parte de este barrio"</span>)</span>
<span id="cb61-237"><a href="#cb61-237" aria-hidden="true" tabindex="-1"></a><span class="fu">get_label</span>(proc_data<span class="sc">$</span>pertenencia)</span>
<span id="cb61-238"><a href="#cb61-238" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-239"><a href="#cb61-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-240"><a href="#cb61-240" aria-hidden="true" tabindex="-1"></a>_Revisión final_</span>
<span id="cb61-241"><a href="#cb61-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-242"><a href="#cb61-242" aria-hidden="true" tabindex="-1"></a>Nuevamente un descriptivo de cada variable para confirmar que el procesamiento está ok:</span>
<span id="cb61-243"><a href="#cb61-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-246"><a href="#cb61-246" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-247"><a href="#cb61-247" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>ideal)</span>
<span id="cb61-248"><a href="#cb61-248" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>integracion)</span>
<span id="cb61-249"><a href="#cb61-249" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>identificacion)</span>
<span id="cb61-250"><a href="#cb61-250" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>pertenencia)</span>
<span id="cb61-251"><a href="#cb61-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-252"><a href="#cb61-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-253"><a href="#cb61-253" aria-hidden="true" tabindex="-1"></a>Vemos que los valores (labels) de cada categoría de las variables que recodificamos no se corresponden con el nuevo valor. Para re-etiquetar valores usamos la función <span class="in">`set_labels`</span>, de la librería <span class="in">`sjlabelled`</span></span>
<span id="cb61-254"><a href="#cb61-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-257"><a href="#cb61-257" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-258"><a href="#cb61-258" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>ideal <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data<span class="sc">$</span>ideal,</span>
<span id="cb61-259"><a href="#cb61-259" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Totalmente en desacuerdo"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb61-260"><a href="#cb61-260" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"En desacuerdo"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb61-261"><a href="#cb61-261" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Ni de acuerdo ni en desacuerdo"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb61-262"><a href="#cb61-262" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"De acuerdo"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb61-263"><a href="#cb61-263" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Totalmente de acuerdo"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb61-264"><a href="#cb61-264" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-265"><a href="#cb61-265" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>integracion <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data<span class="sc">$</span>integracion,</span>
<span id="cb61-266"><a href="#cb61-266" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Totalmente en desacuerdo"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb61-267"><a href="#cb61-267" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"En desacuerdo"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb61-268"><a href="#cb61-268" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Ni de acuerdo ni en desacuerdo"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb61-269"><a href="#cb61-269" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"De acuerdo"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb61-270"><a href="#cb61-270" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Totalmente de acuerdo"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb61-271"><a href="#cb61-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-272"><a href="#cb61-272" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>identificacion <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data<span class="sc">$</span>identificacion,</span>
<span id="cb61-273"><a href="#cb61-273" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Totalmente en desacuerdo"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb61-274"><a href="#cb61-274" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"En desacuerdo"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb61-275"><a href="#cb61-275" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Ni de acuerdo ni en desacuerdo"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb61-276"><a href="#cb61-276" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"De acuerdo"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb61-277"><a href="#cb61-277" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Totalmente de acuerdo"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb61-278"><a href="#cb61-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-279"><a href="#cb61-279" aria-hidden="true" tabindex="-1"></a>proc_data<span class="sc">$</span>pertenencia <span class="ot">&lt;-</span> <span class="fu">set_labels</span>(proc_data<span class="sc">$</span>pertenencia,</span>
<span id="cb61-280"><a href="#cb61-280" aria-hidden="true" tabindex="-1"></a>            <span class="at">labels=</span><span class="fu">c</span>( <span class="st">"Totalmente en desacuerdo"</span><span class="ot">=</span><span class="dv">0</span>,</span>
<span id="cb61-281"><a href="#cb61-281" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"En desacuerdo"</span><span class="ot">=</span><span class="dv">1</span>,</span>
<span id="cb61-282"><a href="#cb61-282" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Ni de acuerdo ni en desacuerdo"</span><span class="ot">=</span><span class="dv">2</span>,</span>
<span id="cb61-283"><a href="#cb61-283" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"De acuerdo"</span><span class="ot">=</span><span class="dv">3</span>,</span>
<span id="cb61-284"><a href="#cb61-284" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Totalmente de acuerdo"</span><span class="ot">=</span><span class="dv">4</span>))</span>
<span id="cb61-285"><a href="#cb61-285" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-286"><a href="#cb61-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-287"><a href="#cb61-287" aria-hidden="true" tabindex="-1"></a>y volvemos a revisar</span>
<span id="cb61-288"><a href="#cb61-288" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-291"><a href="#cb61-291" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-292"><a href="#cb61-292" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>ideal)</span>
<span id="cb61-293"><a href="#cb61-293" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>pertenencia)</span>
<span id="cb61-294"><a href="#cb61-294" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-295"><a href="#cb61-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-296"><a href="#cb61-296" aria-hidden="true" tabindex="-1"></a><span class="fu">#### 4.2. Educación</span></span>
<span id="cb61-297"><a href="#cb61-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-298"><a href="#cb61-298" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span><span class="co">[</span><span class="ot">`m01`</span><span class="co">]</span> =  Nivel de estudios alcanzado - Entrevistado </span>
<span id="cb61-299"><a href="#cb61-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-300"><a href="#cb61-300" aria-hidden="true" tabindex="-1"></a>_a. Descriptivo_</span>
<span id="cb61-301"><a href="#cb61-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-304"><a href="#cb61-304" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-305"><a href="#cb61-305" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m01)</span>
<span id="cb61-306"><a href="#cb61-306" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-307"><a href="#cb61-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-308"><a href="#cb61-308" aria-hidden="true" tabindex="-1"></a>Esta vez la vamos a dejar así</span>
<span id="cb61-309"><a href="#cb61-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-310"><a href="#cb61-310" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.3. Sexo</span></span>
<span id="cb61-311"><a href="#cb61-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-312"><a href="#cb61-312" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span><span class="co">[</span><span class="ot">`m0_sexo`</span><span class="co">]</span>   =   SEXO Sexo</span>
<span id="cb61-313"><a href="#cb61-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-314"><a href="#cb61-314" aria-hidden="true" tabindex="-1"></a>_a. Descriptivo_</span>
<span id="cb61-315"><a href="#cb61-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-318"><a href="#cb61-318" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-319"><a href="#cb61-319" aria-hidden="true" tabindex="-1"></a><span class="fu">frq</span>(proc_data<span class="sc">$</span>m0_sexo)</span>
<span id="cb61-320"><a href="#cb61-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-321"><a href="#cb61-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-322"><a href="#cb61-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-323"><a href="#cb61-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-324"><a href="#cb61-324" aria-hidden="true" tabindex="-1"></a><span class="fu">### 4.4 Edad</span></span>
<span id="cb61-325"><a href="#cb61-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-326"><a href="#cb61-326" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span><span class="co">[</span><span class="ot">`m0_edad`</span><span class="co">]</span>   =   EDAD Edad.</span>
<span id="cb61-327"><a href="#cb61-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-328"><a href="#cb61-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-329"><a href="#cb61-329" aria-hidden="true" tabindex="-1"></a>_a. Descriptivo_</span>
<span id="cb61-330"><a href="#cb61-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-333"><a href="#cb61-333" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-334"><a href="#cb61-334" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data<span class="sc">$</span>m0_edad)</span>
<span id="cb61-335"><a href="#cb61-335" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-336"><a href="#cb61-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-337"><a href="#cb61-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-338"><a href="#cb61-338" aria-hidden="true" tabindex="-1"></a><span class="fu">## 5. Generación de base de datos procesada para el análisis</span></span>
<span id="cb61-339"><a href="#cb61-339" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-340"><a href="#cb61-340" aria-hidden="true" tabindex="-1"></a>Antes de guardar la base procesada, revisamos nuevamente todas las variables con una tabla descriptiva general mediante la función <span class="in">`stargazer`</span> (de la librería homónima)</span>
<span id="cb61-341"><a href="#cb61-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-342"><a href="#cb61-342" aria-hidden="true" tabindex="-1"></a>Primero vamos a reformatear el objeto proc_data como base de datos (as.data.frame), paso necesario para que sea reconocido como tal por <span class="in">`stargazer`</span></span>
<span id="cb61-343"><a href="#cb61-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-344"><a href="#cb61-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-347"><a href="#cb61-347" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-348"><a href="#cb61-348" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span><span class="fu">as.data.frame</span>(proc_data)</span>
<span id="cb61-349"><a href="#cb61-349" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(proc_data, <span class="at">type=</span><span class="st">"text"</span>)</span>
<span id="cb61-350"><a href="#cb61-350" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-351"><a href="#cb61-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-352"><a href="#cb61-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-353"><a href="#cb61-353" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Guardar base de datos procesada: en carpeta local &lt;span class="sidenote"&gt;La ruta hacia su carpeta local si está trabajando en windows debería ser algo como "C:/Users/Lenovo/Clases/y aquí nombre del archivo a grabar&lt;/span&gt;</span>
<span id="cb61-354"><a href="#cb61-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-355"><a href="#cb61-355" aria-hidden="true" tabindex="-1"></a>El comando para guardar es <span class="in">`save`</span>:</span>
<span id="cb61-356"><a href="#cb61-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-357"><a href="#cb61-357" aria-hidden="true" tabindex="-1"></a><span class="in">```{r eval=FALSE}</span></span>
<span id="cb61-358"><a href="#cb61-358" aria-hidden="true" tabindex="-1"></a><span class="in">save(proc_data,file = "[ruta hacia carpeta local en su computador]/ELSOC_ess_merit2016.RData")</span></span>
<span id="cb61-359"><a href="#cb61-359" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-360"><a href="#cb61-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-361"><a href="#cb61-361" aria-hidden="true" tabindex="-1"></a>En este caso, seguimos una estructura de carpetas de datos, separando en una carpeta los datos originales, y en otra (proc) los datos procesados:</span>
<span id="cb61-362"><a href="#cb61-362" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-363"><a href="#cb61-363" aria-hidden="true" tabindex="-1"></a><span class="in">```{r eval=FALSE}</span></span>
<span id="cb61-364"><a href="#cb61-364" aria-hidden="true" tabindex="-1"></a><span class="in">save(proc_data,file = "input/data/elsoc2016_proc.RData")</span></span>
<span id="cb61-365"><a href="#cb61-365" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-366"><a href="#cb61-366" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-367"><a href="#cb61-367" aria-hidden="true" tabindex="-1"></a><span class="fu"># Análisis</span></span>
<span id="cb61-368"><a href="#cb61-368" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-369"><a href="#cb61-369" aria-hidden="true" tabindex="-1"></a>Una vez que tenemos recodificadas nuestras variables en el archivo de preparación y logramos exportar la base de datos procesada en la carpeta input/data, abrimos un documento de quarto (.qmd) para realizar el análisis.</span>
<span id="cb61-370"><a href="#cb61-370" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-371"><a href="#cb61-371" aria-hidden="true" tabindex="-1"></a>Al trabajar con quarto (y al intentar renderizar), el documento leerá todos lo que esté escrito en el documento desde 0, por lo que es necesario **siempre** cargar de nuevo los paquetes y bases de datos.</span>
<span id="cb61-372"><a href="#cb61-372" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-373"><a href="#cb61-373" aria-hidden="true" tabindex="-1"></a>Primero cargamos los paquetes:</span>
<span id="cb61-374"><a href="#cb61-374" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-377"><a href="#cb61-377" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-378"><a href="#cb61-378" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(dplyr, sjmisc, car, sjlabelled, stargazer, haven, sjPlot, ggplot2, psych, kableExtra, corrplot)</span>
<span id="cb61-379"><a href="#cb61-379" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-380"><a href="#cb61-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-381"><a href="#cb61-381" aria-hidden="true" tabindex="-1"></a>y la base procesada</span>
<span id="cb61-382"><a href="#cb61-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-383"><a href="#cb61-383" aria-hidden="true" tabindex="-1"></a><span class="in">```{r eval=FALSE}</span></span>
<span id="cb61-384"><a href="#cb61-384" aria-hidden="true" tabindex="-1"></a><span class="in">load("input/data/elsoc2016_proc.RData")</span></span>
<span id="cb61-385"><a href="#cb61-385" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-386"><a href="#cb61-386" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-387"><a href="#cb61-387" aria-hidden="true" tabindex="-1"></a><span class="fu">### Análisis descriptivo</span></span>
<span id="cb61-388"><a href="#cb61-388" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-391"><a href="#cb61-391" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-392"><a href="#cb61-392" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-sjmisc</span></span>
<span id="cb61-393"><a href="#cb61-393" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Descriptivos"</span></span>
<span id="cb61-394"><a href="#cb61-394" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-395"><a href="#cb61-395" aria-hidden="true" tabindex="-1"></a>sjmisc<span class="sc">::</span><span class="fu">descr</span>(proc_data,</span>
<span id="cb61-396"><a href="#cb61-396" aria-hidden="true" tabindex="-1"></a>      <span class="at">show =</span> <span class="fu">c</span>(<span class="st">"label"</span>,<span class="st">"range"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"NA.prc"</span>, <span class="st">"n"</span>))<span class="sc">%&gt;%</span> <span class="co"># Selecciona estadísticos</span></span>
<span id="cb61-397"><a href="#cb61-397" aria-hidden="true" tabindex="-1"></a>      <span class="fu">kable</span>(.,<span class="st">"markdown"</span>) <span class="co"># Esto es para que se vea bien en quarto</span></span>
<span id="cb61-398"><a href="#cb61-398" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-399"><a href="#cb61-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-400"><a href="#cb61-400" aria-hidden="true" tabindex="-1"></a>En la @tbl-sjmisc podemos observar los descriptivos generales de la base de datos procesada.</span>
<span id="cb61-401"><a href="#cb61-401" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-402"><a href="#cb61-402" aria-hidden="true" tabindex="-1"></a>Y si queremos visualizar algo más:</span>
<span id="cb61-403"><a href="#cb61-403" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-406"><a href="#cb61-406" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-407"><a href="#cb61-407" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-descriptivos</span></span>
<span id="cb61-408"><a href="#cb61-408" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Frecuencias Cohesión barrial"</span></span>
<span id="cb61-409"><a href="#cb61-409" aria-hidden="true" tabindex="-1"></a>proc_data <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(ideal, integracion, identificacion, pertenencia) <span class="sc">%&gt;%</span> </span>
<span id="cb61-410"><a href="#cb61-410" aria-hidden="true" tabindex="-1"></a>  sjPlot<span class="sc">::</span><span class="fu">plot_stackfrq</span>()<span class="sc">+</span></span>
<span id="cb61-411"><a href="#cb61-411" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb61-412"><a href="#cb61-412" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-413"><a href="#cb61-413" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-414"><a href="#cb61-414" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-415"><a href="#cb61-415" aria-hidden="true" tabindex="-1"></a>En la @fig-descriptivos podemos ver la distribución de las variables de cohesión barrial, donde se puede observar que más del 65% de la muestra está de acuerdo o totalmente de acuerdo con las afirmaciones indicadas.</span>
<span id="cb61-416"><a href="#cb61-416" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-417"><a href="#cb61-417" aria-hidden="true" tabindex="-1"></a><span class="fu">### Asociación de variables</span></span>
<span id="cb61-418"><a href="#cb61-418" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-419"><a href="#cb61-419" aria-hidden="true" tabindex="-1"></a>Podemos ver la asociación de todas las variables, como lo muestra la @cor-complete</span>
<span id="cb61-420"><a href="#cb61-420" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-423"><a href="#cb61-423" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-424"><a href="#cb61-424" aria-hidden="true" tabindex="-1"></a>M <span class="ot">&lt;-</span> <span class="fu">cor</span>(proc_data, <span class="at">use =</span> <span class="st">"complete.obs"</span>) <span class="co"># Usar solo casos con observaciones completas</span></span>
<span id="cb61-425"><a href="#cb61-425" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-426"><a href="#cb61-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-429"><a href="#cb61-429" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-430"><a href="#cb61-430" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: cor-complete</span></span>
<span id="cb61-431"><a href="#cb61-431" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Cohesión variables elsoc 2016"</span></span>
<span id="cb61-432"><a href="#cb61-432" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-433"><a href="#cb61-433" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-434"><a href="#cb61-434" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(M)</span>
<span id="cb61-435"><a href="#cb61-435" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-436"><a href="#cb61-436" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-437"><a href="#cb61-437" aria-hidden="true" tabindex="-1"></a>o podemos ver específicamente la asociación de las variables de cohesión barrial</span>
<span id="cb61-438"><a href="#cb61-438" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-441"><a href="#cb61-441" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-442"><a href="#cb61-442" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-cor-cohesion</span></span>
<span id="cb61-443"><a href="#cb61-443" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Correlación Cohesión barrial"</span></span>
<span id="cb61-444"><a href="#cb61-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-445"><a href="#cb61-445" aria-hidden="true" tabindex="-1"></a>M2 <span class="ot">&lt;-</span> <span class="fu">cor</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data, ideal, integracion, identificacion, pertenencia), <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb61-446"><a href="#cb61-446" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot.mixed</span>(M2)</span>
<span id="cb61-447"><a href="#cb61-447" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-448"><a href="#cb61-448" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-449"><a href="#cb61-449" aria-hidden="true" tabindex="-1"></a>La @fig-cor-cohesion muestra que la asociación de las cuatro variables de cohesión barrial es alta y positiva, según Cohen (1998). En general el tamaño de efecto varía entre 0.58 la más baja y 0.69 la más alta.</span>
<span id="cb61-450"><a href="#cb61-450" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-451"><a href="#cb61-451" aria-hidden="true" tabindex="-1"></a><span class="fu">### Construcción de escala</span></span>
<span id="cb61-452"><a href="#cb61-452" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-455"><a href="#cb61-455" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-456"><a href="#cb61-456" aria-hidden="true" tabindex="-1"></a>psych<span class="sc">::</span><span class="fu">alpha</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(proc_data, ideal, integracion, identificacion, pertenencia))</span>
<span id="cb61-457"><a href="#cb61-457" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-458"><a href="#cb61-458" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-459"><a href="#cb61-459" aria-hidden="true" tabindex="-1"></a>La consistencia interna de una posible escala entre estos cuatro ítems es de 0.87, lo que representa una alta consistencia interna. Si quitaramos alguno de estos ítems la consistencia interna solo bajaría, así que podemos construir una escala con los cuatro ítems.</span>
<span id="cb61-460"><a href="#cb61-460" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-463"><a href="#cb61-463" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-464"><a href="#cb61-464" aria-hidden="true" tabindex="-1"></a>proc_data <span class="ot">&lt;-</span> proc_data <span class="sc">%&gt;%</span> </span>
<span id="cb61-465"><a href="#cb61-465" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb61-466"><a href="#cb61-466" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">cohesion_barrial =</span> <span class="fu">sum</span>(ideal, integracion, identificacion, pertenencia))</span>
<span id="cb61-467"><a href="#cb61-467" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(proc_data<span class="sc">$</span>cohesion_barrial)</span>
<span id="cb61-468"><a href="#cb61-468" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-469"><a href="#cb61-469" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-470"><a href="#cb61-470" aria-hidden="true" tabindex="-1"></a>y la podemos visualizar en un gráfico:</span>
<span id="cb61-471"><a href="#cb61-471" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-474"><a href="#cb61-474" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb61-475"><a href="#cb61-475" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-plot-cohesion</span></span>
<span id="cb61-476"><a href="#cb61-476" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Histograma Cohesión barrial"</span></span>
<span id="cb61-477"><a href="#cb61-477" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-478"><a href="#cb61-478" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-479"><a href="#cb61-479" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proc_data, <span class="fu">aes</span>(<span class="at">x =</span> cohesion_barrial)) <span class="sc">+</span></span>
<span id="cb61-480"><a href="#cb61-480" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="fl">0.6</span>, <span class="at">colour=</span><span class="st">"black"</span>, <span class="at">fill=</span><span class="st">"yellow"</span>) <span class="sc">+</span></span>
<span id="cb61-481"><a href="#cb61-481" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb61-482"><a href="#cb61-482" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Cohesión barrial"</span>) <span class="sc">+</span></span>
<span id="cb61-483"><a href="#cb61-483" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Cantidad"</span>)</span>
<span id="cb61-484"><a href="#cb61-484" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb61-485"><a href="#cb61-485" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-486"><a href="#cb61-486" aria-hidden="true" tabindex="-1"></a>La @fig-plot-cohesion muestra la distribución de la nueva escala de Cohesión Barrial que construimos. En general, la mayor concentración de casos está en la categoría 12 y que sumado a un promedio de 10.33 según los descriptivos anteriores, podríamos afirmar que la cohesión barrial en Chile es alta.</span>
<span id="cb61-487"><a href="#cb61-487" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-488"><a href="#cb61-488" aria-hidden="true" tabindex="-1"></a><span class="fu"># Subir a github</span></span>
<span id="cb61-489"><a href="#cb61-489" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-490"><a href="#cb61-490" aria-hidden="true" tabindex="-1"></a>Una vez que tenemos nuestro cambios hechos, vamos a Github desktop y seguimos los siguientes pasos:</span>
<span id="cb61-491"><a href="#cb61-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-492"><a href="#cb61-492" aria-hidden="true" tabindex="-1"></a><span class="al">![](../files/img/upload-github.png)</span></span>
</code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Content <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> 2024 by Kevin Carrasco <br> All content licensed under a <i class="fa-brands fa-creative-commons" aria-label="creative-commons"></i> <i class="fa-brands fa-creative-commons-by" aria-label="creative-commons-by"></i> <i class="fa-brands fa-creative-commons-nc" aria-label="creative-commons-nc"></i> <a href="https://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)</a></p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Made with <i class="fa-brands fa-r-project" aria-label="r-project"></i> and <a href="https://quarto.org/">Quarto</a><br> <a href="https://github.com/Kevin-carrasco/R-data-analisis">View the source at <i class="fa-brands fa-github" aria-label="github"></i> GitHub</a></p>
</div>
  </div>
</footer>




</body></html>